// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/solo-io/squash/pkg/models"
)

// NewAddDebugAttachmentParams creates a new AddDebugAttachmentParams object
// with the default values initialized.
func NewAddDebugAttachmentParams() *AddDebugAttachmentParams {
	var ()
	return &AddDebugAttachmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddDebugAttachmentParamsWithTimeout creates a new AddDebugAttachmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddDebugAttachmentParamsWithTimeout(timeout time.Duration) *AddDebugAttachmentParams {
	var ()
	return &AddDebugAttachmentParams{

		timeout: timeout,
	}
}

// NewAddDebugAttachmentParamsWithContext creates a new AddDebugAttachmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddDebugAttachmentParamsWithContext(ctx context.Context) *AddDebugAttachmentParams {
	var ()
	return &AddDebugAttachmentParams{

		Context: ctx,
	}
}

// NewAddDebugAttachmentParamsWithHTTPClient creates a new AddDebugAttachmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddDebugAttachmentParamsWithHTTPClient(client *http.Client) *AddDebugAttachmentParams {
	var ()
	return &AddDebugAttachmentParams{
		HTTPClient: client,
	}
}

/*AddDebugAttachmentParams contains all the parameters to send to the API endpoint
for the add debug attachment operation typically these are written to a http.Request
*/
type AddDebugAttachmentParams struct {

	/*Body
	  DebugAttachment object

	*/
	Body *models.DebugAttachment

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add debug attachment params
func (o *AddDebugAttachmentParams) WithTimeout(timeout time.Duration) *AddDebugAttachmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add debug attachment params
func (o *AddDebugAttachmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add debug attachment params
func (o *AddDebugAttachmentParams) WithContext(ctx context.Context) *AddDebugAttachmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add debug attachment params
func (o *AddDebugAttachmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add debug attachment params
func (o *AddDebugAttachmentParams) WithHTTPClient(client *http.Client) *AddDebugAttachmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add debug attachment params
func (o *AddDebugAttachmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add debug attachment params
func (o *AddDebugAttachmentParams) WithBody(body *models.DebugAttachment) *AddDebugAttachmentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add debug attachment params
func (o *AddDebugAttachmentParams) SetBody(body *models.DebugAttachment) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddDebugAttachmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
