// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDebugAttachmentParams creates a new DeleteDebugAttachmentParams object
// with the default values initialized.
func NewDeleteDebugAttachmentParams() *DeleteDebugAttachmentParams {
	var ()
	return &DeleteDebugAttachmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDebugAttachmentParamsWithTimeout creates a new DeleteDebugAttachmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDebugAttachmentParamsWithTimeout(timeout time.Duration) *DeleteDebugAttachmentParams {
	var ()
	return &DeleteDebugAttachmentParams{

		timeout: timeout,
	}
}

// NewDeleteDebugAttachmentParamsWithContext creates a new DeleteDebugAttachmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDebugAttachmentParamsWithContext(ctx context.Context) *DeleteDebugAttachmentParams {
	var ()
	return &DeleteDebugAttachmentParams{

		Context: ctx,
	}
}

// NewDeleteDebugAttachmentParamsWithHTTPClient creates a new DeleteDebugAttachmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDebugAttachmentParamsWithHTTPClient(client *http.Client) *DeleteDebugAttachmentParams {
	var ()
	return &DeleteDebugAttachmentParams{
		HTTPClient: client,
	}
}

/*DeleteDebugAttachmentParams contains all the parameters to send to the API endpoint
for the delete debug attachment operation typically these are written to a http.Request
*/
type DeleteDebugAttachmentParams struct {

	/*DebugAttachmentID
	  ID of config to return

	*/
	DebugAttachmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) WithTimeout(timeout time.Duration) *DeleteDebugAttachmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) WithContext(ctx context.Context) *DeleteDebugAttachmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) WithHTTPClient(client *http.Client) *DeleteDebugAttachmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDebugAttachmentID adds the debugAttachmentID to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) WithDebugAttachmentID(debugAttachmentID string) *DeleteDebugAttachmentParams {
	o.SetDebugAttachmentID(debugAttachmentID)
	return o
}

// SetDebugAttachmentID adds the debugAttachmentId to the delete debug attachment params
func (o *DeleteDebugAttachmentParams) SetDebugAttachmentID(debugAttachmentID string) {
	o.DebugAttachmentID = debugAttachmentID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDebugAttachmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param debugAttachmentId
	if err := r.SetPathParam("debugAttachmentId", o.DebugAttachmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
