// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDebugAttachmentReader is a Reader for the DeleteDebugAttachment structure.
type DeleteDebugAttachmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDebugAttachmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDebugAttachmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteDebugAttachmentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteDebugAttachmentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewDeleteDebugAttachmentUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDebugAttachmentOK creates a DeleteDebugAttachmentOK with default headers values
func NewDeleteDebugAttachmentOK() *DeleteDebugAttachmentOK {
	return &DeleteDebugAttachmentOK{}
}

/*DeleteDebugAttachmentOK handles this case with default header values.

OK
*/
type DeleteDebugAttachmentOK struct {
}

func (o *DeleteDebugAttachmentOK) Error() string {
	return fmt.Sprintf("[DELETE /debugattachment/{debugAttachmentId}][%d] deleteDebugAttachmentOK ", 200)
}

func (o *DeleteDebugAttachmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDebugAttachmentBadRequest creates a DeleteDebugAttachmentBadRequest with default headers values
func NewDeleteDebugAttachmentBadRequest() *DeleteDebugAttachmentBadRequest {
	return &DeleteDebugAttachmentBadRequest{}
}

/*DeleteDebugAttachmentBadRequest handles this case with default header values.

Invalid ID supplied
*/
type DeleteDebugAttachmentBadRequest struct {
}

func (o *DeleteDebugAttachmentBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /debugattachment/{debugAttachmentId}][%d] deleteDebugAttachmentBadRequest ", 400)
}

func (o *DeleteDebugAttachmentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDebugAttachmentNotFound creates a DeleteDebugAttachmentNotFound with default headers values
func NewDeleteDebugAttachmentNotFound() *DeleteDebugAttachmentNotFound {
	return &DeleteDebugAttachmentNotFound{}
}

/*DeleteDebugAttachmentNotFound handles this case with default header values.

Debug config not found
*/
type DeleteDebugAttachmentNotFound struct {
}

func (o *DeleteDebugAttachmentNotFound) Error() string {
	return fmt.Sprintf("[DELETE /debugattachment/{debugAttachmentId}][%d] deleteDebugAttachmentNotFound ", 404)
}

func (o *DeleteDebugAttachmentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDebugAttachmentUnprocessableEntity creates a DeleteDebugAttachmentUnprocessableEntity with default headers values
func NewDeleteDebugAttachmentUnprocessableEntity() *DeleteDebugAttachmentUnprocessableEntity {
	return &DeleteDebugAttachmentUnprocessableEntity{}
}

/*DeleteDebugAttachmentUnprocessableEntity handles this case with default header values.

Validation exception
*/
type DeleteDebugAttachmentUnprocessableEntity struct {
}

func (o *DeleteDebugAttachmentUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /debugattachment/{debugAttachmentId}][%d] deleteDebugAttachmentUnprocessableEntity ", 422)
}

func (o *DeleteDebugAttachmentUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
