apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: squash-demo-cpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squash-demo-cpp
  template:
    metadata:
      labels:
        app: squash-demo-cpp
    spec:
      containers:
      - name: squash-demo-cpp
        image: docker.io/soloio/squash-demo-cpp:v0.0.1
        ports:
        - containerPort: 8080
          protocol: TCP
