// Squash by Solo.io

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	squash_v1 "github.com/solo-io/squash/pkg/platforms/kubernetes/crd/apis/squash/v1"
	versioned "github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/clientset/versioned"
	internalinterfaces "github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/informers/externalversions/internalinterfaces"
	v1 "github.com/solo-io/squash/pkg/platforms/kubernetes/crd/client/listers/squash/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DebugRequestInformer provides access to a shared informer and lister for
// DebugRequests.
type DebugRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DebugRequestLister
}

type debugRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDebugRequestInformer constructs a new informer for DebugRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDebugRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDebugRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDebugRequestInformer constructs a new informer for DebugRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDebugRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SquashV1().DebugRequests(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SquashV1().DebugRequests(namespace).Watch(options)
			},
		},
		&squash_v1.DebugRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *debugRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDebugRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *debugRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&squash_v1.DebugRequest{}, f.defaultInformer)
}

func (f *debugRequestInformer) Lister() v1.DebugRequestLister {
	return v1.NewDebugRequestLister(f.Informer().GetIndexer())
}
