FROM golang:1.14.9-stretch  as builder

ENV GO111MODULE on

RUN go get github.com/go-delve/delve/cmd/dlv@v1.5.0


FROM golang:1.14.9-stretch  

COPY --from=builder $GOPATH/bin/dlv $GOPATH/bin/

ENV DEBUGGER=dlv
COPY plank /
ENTRYPOINT ["/plank"]
