// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Squash Server
Squash debugger api.


    Schemes:
      http
    Host: localhost
    BasePath: /api/v2
    Version: 2.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <apiteam@solo.io>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
