// Squash by Solo.io

// This file was automatically generated by lister-gen

package v1

// DebugAttachmentListerExpansion allows custom methods to be added to
// DebugAttachmentLister.
type DebugAttachmentListerExpansion interface{}

// DebugAttachmentNamespaceListerExpansion allows custom methods to be added to
// DebugAttachmentNamespaceLister.
type DebugAttachmentNamespaceListerExpansion interface{}

// DebugRequestListerExpansion allows custom methods to be added to
// DebugRequestLister.
type DebugRequestListerExpansion interface{}

// DebugRequestNamespaceListerExpansion allows custom methods to be added to
// DebugRequestNamespaceLister.
type DebugRequestNamespaceListerExpansion interface{}
