// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/solo-io/squash/pkg/models"
)

// NewCreateDebugRequestParams creates a new CreateDebugRequestParams object
// with the default values initialized.
func NewCreateDebugRequestParams() *CreateDebugRequestParams {
	var ()
	return &CreateDebugRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDebugRequestParamsWithTimeout creates a new CreateDebugRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDebugRequestParamsWithTimeout(timeout time.Duration) *CreateDebugRequestParams {
	var ()
	return &CreateDebugRequestParams{

		timeout: timeout,
	}
}

// NewCreateDebugRequestParamsWithContext creates a new CreateDebugRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDebugRequestParamsWithContext(ctx context.Context) *CreateDebugRequestParams {
	var ()
	return &CreateDebugRequestParams{

		Context: ctx,
	}
}

// NewCreateDebugRequestParamsWithHTTPClient creates a new CreateDebugRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDebugRequestParamsWithHTTPClient(client *http.Client) *CreateDebugRequestParams {
	var ()
	return &CreateDebugRequestParams{
		HTTPClient: client,
	}
}

/*CreateDebugRequestParams contains all the parameters to send to the API endpoint
for the create debug request operation typically these are written to a http.Request
*/
type CreateDebugRequestParams struct {

	/*Body
	  DebugRequest object

	*/
	Body *models.DebugRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create debug request params
func (o *CreateDebugRequestParams) WithTimeout(timeout time.Duration) *CreateDebugRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create debug request params
func (o *CreateDebugRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create debug request params
func (o *CreateDebugRequestParams) WithContext(ctx context.Context) *CreateDebugRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create debug request params
func (o *CreateDebugRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create debug request params
func (o *CreateDebugRequestParams) WithHTTPClient(client *http.Client) *CreateDebugRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create debug request params
func (o *CreateDebugRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create debug request params
func (o *CreateDebugRequestParams) WithBody(body *models.DebugRequest) *CreateDebugRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create debug request params
func (o *CreateDebugRequestParams) SetBody(body *models.DebugRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDebugRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
