// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDebugRequestParams creates a new DeleteDebugRequestParams object
// with the default values initialized.
func NewDeleteDebugRequestParams() *DeleteDebugRequestParams {
	var ()
	return &DeleteDebugRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDebugRequestParamsWithTimeout creates a new DeleteDebugRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDebugRequestParamsWithTimeout(timeout time.Duration) *DeleteDebugRequestParams {
	var ()
	return &DeleteDebugRequestParams{

		timeout: timeout,
	}
}

// NewDeleteDebugRequestParamsWithContext creates a new DeleteDebugRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDebugRequestParamsWithContext(ctx context.Context) *DeleteDebugRequestParams {
	var ()
	return &DeleteDebugRequestParams{

		Context: ctx,
	}
}

// NewDeleteDebugRequestParamsWithHTTPClient creates a new DeleteDebugRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDebugRequestParamsWithHTTPClient(client *http.Client) *DeleteDebugRequestParams {
	var ()
	return &DeleteDebugRequestParams{
		HTTPClient: client,
	}
}

/*DeleteDebugRequestParams contains all the parameters to send to the API endpoint
for the delete debug request operation typically these are written to a http.Request
*/
type DeleteDebugRequestParams struct {

	/*DebugRequestID
	  ID of debug request

	*/
	DebugRequestID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete debug request params
func (o *DeleteDebugRequestParams) WithTimeout(timeout time.Duration) *DeleteDebugRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete debug request params
func (o *DeleteDebugRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete debug request params
func (o *DeleteDebugRequestParams) WithContext(ctx context.Context) *DeleteDebugRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete debug request params
func (o *DeleteDebugRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete debug request params
func (o *DeleteDebugRequestParams) WithHTTPClient(client *http.Client) *DeleteDebugRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete debug request params
func (o *DeleteDebugRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDebugRequestID adds the debugRequestID to the delete debug request params
func (o *DeleteDebugRequestParams) WithDebugRequestID(debugRequestID string) *DeleteDebugRequestParams {
	o.SetDebugRequestID(debugRequestID)
	return o
}

// SetDebugRequestID adds the debugRequestId to the delete debug request params
func (o *DeleteDebugRequestParams) SetDebugRequestID(debugRequestID string) {
	o.DebugRequestID = debugRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDebugRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param debugRequestId
	if err := r.SetPathParam("debugRequestId", o.DebugRequestID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
