// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDebugRequestsParams creates a new GetDebugRequestsParams object
// with the default values initialized.
func NewGetDebugRequestsParams() *GetDebugRequestsParams {

	return &GetDebugRequestsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDebugRequestsParamsWithTimeout creates a new GetDebugRequestsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDebugRequestsParamsWithTimeout(timeout time.Duration) *GetDebugRequestsParams {

	return &GetDebugRequestsParams{

		timeout: timeout,
	}
}

// NewGetDebugRequestsParamsWithContext creates a new GetDebugRequestsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDebugRequestsParamsWithContext(ctx context.Context) *GetDebugRequestsParams {

	return &GetDebugRequestsParams{

		Context: ctx,
	}
}

// NewGetDebugRequestsParamsWithHTTPClient creates a new GetDebugRequestsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDebugRequestsParamsWithHTTPClient(client *http.Client) *GetDebugRequestsParams {

	return &GetDebugRequestsParams{
		HTTPClient: client,
	}
}

/*GetDebugRequestsParams contains all the parameters to send to the API endpoint
for the get debug requests operation typically these are written to a http.Request
*/
type GetDebugRequestsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get debug requests params
func (o *GetDebugRequestsParams) WithTimeout(timeout time.Duration) *GetDebugRequestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get debug requests params
func (o *GetDebugRequestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get debug requests params
func (o *GetDebugRequestsParams) WithContext(ctx context.Context) *GetDebugRequestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get debug requests params
func (o *GetDebugRequestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get debug requests params
func (o *GetDebugRequestsParams) WithHTTPClient(client *http.Client) *GetDebugRequestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get debug requests params
func (o *GetDebugRequestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDebugRequestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
