// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/solo-io/squash/pkg/restapi/operations/debugattachment"
	"github.com/solo-io/squash/pkg/restapi/operations/debugrequest"
)

// NewSquashAPI creates a new Squash instance
func NewSquashAPI(spec *loads.Document) *SquashAPI {
	return &SquashAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		DebugattachmentAddDebugAttachmentHandler: debugattachment.AddDebugAttachmentHandlerFunc(func(params debugattachment.AddDebugAttachmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugattachmentAddDebugAttachment has not yet been implemented")
		}),
		DebugrequestCreateDebugRequestHandler: debugrequest.CreateDebugRequestHandlerFunc(func(params debugrequest.CreateDebugRequestParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugrequestCreateDebugRequest has not yet been implemented")
		}),
		DebugattachmentDeleteDebugAttachmentHandler: debugattachment.DeleteDebugAttachmentHandlerFunc(func(params debugattachment.DeleteDebugAttachmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugattachmentDeleteDebugAttachment has not yet been implemented")
		}),
		DebugrequestDeleteDebugRequestHandler: debugrequest.DeleteDebugRequestHandlerFunc(func(params debugrequest.DeleteDebugRequestParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugrequestDeleteDebugRequest has not yet been implemented")
		}),
		DebugattachmentGetDebugAttachmentHandler: debugattachment.GetDebugAttachmentHandlerFunc(func(params debugattachment.GetDebugAttachmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugattachmentGetDebugAttachment has not yet been implemented")
		}),
		DebugattachmentGetDebugAttachmentsHandler: debugattachment.GetDebugAttachmentsHandlerFunc(func(params debugattachment.GetDebugAttachmentsParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugattachmentGetDebugAttachments has not yet been implemented")
		}),
		DebugrequestGetDebugRequestHandler: debugrequest.GetDebugRequestHandlerFunc(func(params debugrequest.GetDebugRequestParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugrequestGetDebugRequest has not yet been implemented")
		}),
		DebugrequestGetDebugRequestsHandler: debugrequest.GetDebugRequestsHandlerFunc(func(params debugrequest.GetDebugRequestsParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugrequestGetDebugRequests has not yet been implemented")
		}),
		DebugattachmentPatchDebugAttachmentHandler: debugattachment.PatchDebugAttachmentHandlerFunc(func(params debugattachment.PatchDebugAttachmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DebugattachmentPatchDebugAttachment has not yet been implemented")
		}),
	}
}

/*SquashAPI Squash debugger api. */
type SquashAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// DebugattachmentAddDebugAttachmentHandler sets the operation handler for the add debug attachment operation
	DebugattachmentAddDebugAttachmentHandler debugattachment.AddDebugAttachmentHandler
	// DebugrequestCreateDebugRequestHandler sets the operation handler for the create debug request operation
	DebugrequestCreateDebugRequestHandler debugrequest.CreateDebugRequestHandler
	// DebugattachmentDeleteDebugAttachmentHandler sets the operation handler for the delete debug attachment operation
	DebugattachmentDeleteDebugAttachmentHandler debugattachment.DeleteDebugAttachmentHandler
	// DebugrequestDeleteDebugRequestHandler sets the operation handler for the delete debug request operation
	DebugrequestDeleteDebugRequestHandler debugrequest.DeleteDebugRequestHandler
	// DebugattachmentGetDebugAttachmentHandler sets the operation handler for the get debug attachment operation
	DebugattachmentGetDebugAttachmentHandler debugattachment.GetDebugAttachmentHandler
	// DebugattachmentGetDebugAttachmentsHandler sets the operation handler for the get debug attachments operation
	DebugattachmentGetDebugAttachmentsHandler debugattachment.GetDebugAttachmentsHandler
	// DebugrequestGetDebugRequestHandler sets the operation handler for the get debug request operation
	DebugrequestGetDebugRequestHandler debugrequest.GetDebugRequestHandler
	// DebugrequestGetDebugRequestsHandler sets the operation handler for the get debug requests operation
	DebugrequestGetDebugRequestsHandler debugrequest.GetDebugRequestsHandler
	// DebugattachmentPatchDebugAttachmentHandler sets the operation handler for the patch debug attachment operation
	DebugattachmentPatchDebugAttachmentHandler debugattachment.PatchDebugAttachmentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SquashAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SquashAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SquashAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SquashAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SquashAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SquashAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SquashAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SquashAPI
func (o *SquashAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.DebugattachmentAddDebugAttachmentHandler == nil {
		unregistered = append(unregistered, "debugattachment.AddDebugAttachmentHandler")
	}

	if o.DebugrequestCreateDebugRequestHandler == nil {
		unregistered = append(unregistered, "debugrequest.CreateDebugRequestHandler")
	}

	if o.DebugattachmentDeleteDebugAttachmentHandler == nil {
		unregistered = append(unregistered, "debugattachment.DeleteDebugAttachmentHandler")
	}

	if o.DebugrequestDeleteDebugRequestHandler == nil {
		unregistered = append(unregistered, "debugrequest.DeleteDebugRequestHandler")
	}

	if o.DebugattachmentGetDebugAttachmentHandler == nil {
		unregistered = append(unregistered, "debugattachment.GetDebugAttachmentHandler")
	}

	if o.DebugattachmentGetDebugAttachmentsHandler == nil {
		unregistered = append(unregistered, "debugattachment.GetDebugAttachmentsHandler")
	}

	if o.DebugrequestGetDebugRequestHandler == nil {
		unregistered = append(unregistered, "debugrequest.GetDebugRequestHandler")
	}

	if o.DebugrequestGetDebugRequestsHandler == nil {
		unregistered = append(unregistered, "debugrequest.GetDebugRequestsHandler")
	}

	if o.DebugattachmentPatchDebugAttachmentHandler == nil {
		unregistered = append(unregistered, "debugattachment.PatchDebugAttachmentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SquashAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SquashAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *SquashAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *SquashAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *SquashAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SquashAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the squash API
func (o *SquashAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SquashAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/debugattachment"] = debugattachment.NewAddDebugAttachment(o.context, o.DebugattachmentAddDebugAttachmentHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/debugrequest"] = debugrequest.NewCreateDebugRequest(o.context, o.DebugrequestCreateDebugRequestHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/debugattachment/{debugAttachmentId}"] = debugattachment.NewDeleteDebugAttachment(o.context, o.DebugattachmentDeleteDebugAttachmentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/debugrequest/{debugRequestId}"] = debugrequest.NewDeleteDebugRequest(o.context, o.DebugrequestDeleteDebugRequestHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/debugattachment/{debugAttachmentId}"] = debugattachment.NewGetDebugAttachment(o.context, o.DebugattachmentGetDebugAttachmentHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/debugattachment"] = debugattachment.NewGetDebugAttachments(o.context, o.DebugattachmentGetDebugAttachmentsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/debugrequest/{debugRequestId}"] = debugrequest.NewGetDebugRequest(o.context, o.DebugrequestGetDebugRequestHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/debugrequest"] = debugrequest.NewGetDebugRequests(o.context, o.DebugrequestGetDebugRequestsHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/debugattachment/{debugAttachmentId}"] = debugattachment.NewPatchDebugAttachment(o.context, o.DebugattachmentPatchDebugAttachmentHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SquashAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *SquashAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
