// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// AddDebugAttachmentCreatedCode is the HTTP code returned for type AddDebugAttachmentCreated
const AddDebugAttachmentCreatedCode int = 201

/*AddDebugAttachmentCreated Debug attachment created

swagger:response addDebugAttachmentCreated
*/
type AddDebugAttachmentCreated struct {

	/*
	  In: Body
	*/
	Payload *models.DebugAttachment `json:"body,omitempty"`
}

// NewAddDebugAttachmentCreated creates AddDebugAttachmentCreated with default headers values
func NewAddDebugAttachmentCreated() *AddDebugAttachmentCreated {
	return &AddDebugAttachmentCreated{}
}

// WithPayload adds the payload to the add debug attachment created response
func (o *AddDebugAttachmentCreated) WithPayload(payload *models.DebugAttachment) *AddDebugAttachmentCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add debug attachment created response
func (o *AddDebugAttachmentCreated) SetPayload(payload *models.DebugAttachment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddDebugAttachmentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddDebugAttachmentBadRequestCode is the HTTP code returned for type AddDebugAttachmentBadRequest
const AddDebugAttachmentBadRequestCode int = 400

/*AddDebugAttachmentBadRequest Bad request

swagger:response addDebugAttachmentBadRequest
*/
type AddDebugAttachmentBadRequest struct {
}

// NewAddDebugAttachmentBadRequest creates AddDebugAttachmentBadRequest with default headers values
func NewAddDebugAttachmentBadRequest() *AddDebugAttachmentBadRequest {
	return &AddDebugAttachmentBadRequest{}
}

// WriteResponse to the client
func (o *AddDebugAttachmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddDebugAttachmentNotFoundCode is the HTTP code returned for type AddDebugAttachmentNotFound
const AddDebugAttachmentNotFoundCode int = 404

/*AddDebugAttachmentNotFound Not found

swagger:response addDebugAttachmentNotFound
*/
type AddDebugAttachmentNotFound struct {
}

// NewAddDebugAttachmentNotFound creates AddDebugAttachmentNotFound with default headers values
func NewAddDebugAttachmentNotFound() *AddDebugAttachmentNotFound {
	return &AddDebugAttachmentNotFound{}
}

// WriteResponse to the client
func (o *AddDebugAttachmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// AddDebugAttachmentUnprocessableEntityCode is the HTTP code returned for type AddDebugAttachmentUnprocessableEntity
const AddDebugAttachmentUnprocessableEntityCode int = 422

/*AddDebugAttachmentUnprocessableEntity Invalid input

swagger:response addDebugAttachmentUnprocessableEntity
*/
type AddDebugAttachmentUnprocessableEntity struct {
}

// NewAddDebugAttachmentUnprocessableEntity creates AddDebugAttachmentUnprocessableEntity with default headers values
func NewAddDebugAttachmentUnprocessableEntity() *AddDebugAttachmentUnprocessableEntity {
	return &AddDebugAttachmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *AddDebugAttachmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// AddDebugAttachmentServiceUnavailableCode is the HTTP code returned for type AddDebugAttachmentServiceUnavailable
const AddDebugAttachmentServiceUnavailableCode int = 503

/*AddDebugAttachmentServiceUnavailable Service Unavailable

swagger:response addDebugAttachmentServiceUnavailable
*/
type AddDebugAttachmentServiceUnavailable struct {
}

// NewAddDebugAttachmentServiceUnavailable creates AddDebugAttachmentServiceUnavailable with default headers values
func NewAddDebugAttachmentServiceUnavailable() *AddDebugAttachmentServiceUnavailable {
	return &AddDebugAttachmentServiceUnavailable{}
}

// WriteResponse to the client
func (o *AddDebugAttachmentServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
