// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDebugAttachmentParams creates a new DeleteDebugAttachmentParams object
// with the default values initialized.
func NewDeleteDebugAttachmentParams() DeleteDebugAttachmentParams {
	var ()
	return DeleteDebugAttachmentParams{}
}

// DeleteDebugAttachmentParams contains all the bound params for the delete debug attachment operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteDebugAttachment
type DeleteDebugAttachmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of config to return
	  Required: true
	  In: path
	*/
	DebugAttachmentID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteDebugAttachmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rDebugAttachmentID, rhkDebugAttachmentID, _ := route.Params.GetOK("debugAttachmentId")
	if err := o.bindDebugAttachmentID(rDebugAttachmentID, rhkDebugAttachmentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDebugAttachmentParams) bindDebugAttachmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DebugAttachmentID = raw

	return nil
}
