// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDebugAttachmentOKCode is the HTTP code returned for type DeleteDebugAttachmentOK
const DeleteDebugAttachmentOKCode int = 200

/*DeleteDebugAttachmentOK OK

swagger:response deleteDebugAttachmentOK
*/
type DeleteDebugAttachmentOK struct {
}

// NewDeleteDebugAttachmentOK creates DeleteDebugAttachmentOK with default headers values
func NewDeleteDebugAttachmentOK() *DeleteDebugAttachmentOK {
	return &DeleteDebugAttachmentOK{}
}

// WriteResponse to the client
func (o *DeleteDebugAttachmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteDebugAttachmentBadRequestCode is the HTTP code returned for type DeleteDebugAttachmentBadRequest
const DeleteDebugAttachmentBadRequestCode int = 400

/*DeleteDebugAttachmentBadRequest Invalid ID supplied

swagger:response deleteDebugAttachmentBadRequest
*/
type DeleteDebugAttachmentBadRequest struct {
}

// NewDeleteDebugAttachmentBadRequest creates DeleteDebugAttachmentBadRequest with default headers values
func NewDeleteDebugAttachmentBadRequest() *DeleteDebugAttachmentBadRequest {
	return &DeleteDebugAttachmentBadRequest{}
}

// WriteResponse to the client
func (o *DeleteDebugAttachmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteDebugAttachmentNotFoundCode is the HTTP code returned for type DeleteDebugAttachmentNotFound
const DeleteDebugAttachmentNotFoundCode int = 404

/*DeleteDebugAttachmentNotFound Debug config not found

swagger:response deleteDebugAttachmentNotFound
*/
type DeleteDebugAttachmentNotFound struct {
}

// NewDeleteDebugAttachmentNotFound creates DeleteDebugAttachmentNotFound with default headers values
func NewDeleteDebugAttachmentNotFound() *DeleteDebugAttachmentNotFound {
	return &DeleteDebugAttachmentNotFound{}
}

// WriteResponse to the client
func (o *DeleteDebugAttachmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteDebugAttachmentUnprocessableEntityCode is the HTTP code returned for type DeleteDebugAttachmentUnprocessableEntity
const DeleteDebugAttachmentUnprocessableEntityCode int = 422

/*DeleteDebugAttachmentUnprocessableEntity Validation exception

swagger:response deleteDebugAttachmentUnprocessableEntity
*/
type DeleteDebugAttachmentUnprocessableEntity struct {
}

// NewDeleteDebugAttachmentUnprocessableEntity creates DeleteDebugAttachmentUnprocessableEntity with default headers values
func NewDeleteDebugAttachmentUnprocessableEntity() *DeleteDebugAttachmentUnprocessableEntity {
	return &DeleteDebugAttachmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *DeleteDebugAttachmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
