// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDebugAttachmentsHandlerFunc turns a function with the right signature into a get debug attachments handler
type GetDebugAttachmentsHandlerFunc func(GetDebugAttachmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDebugAttachmentsHandlerFunc) Handle(params GetDebugAttachmentsParams) middleware.Responder {
	return fn(params)
}

// GetDebugAttachmentsHandler interface for that can handle valid get debug attachments params
type GetDebugAttachmentsHandler interface {
	Handle(GetDebugAttachmentsParams) middleware.Responder
}

// NewGetDebugAttachments creates a new http.Handler for the get debug attachments operation
func NewGetDebugAttachments(ctx *middleware.Context, handler GetDebugAttachmentsHandler) *GetDebugAttachments {
	return &GetDebugAttachments{Context: ctx, Handler: handler}
}

/*GetDebugAttachments swagger:route GET /debugattachment debugattachment getDebugAttachments

Return all debug attachment

Return all debug attachment

*/
type GetDebugAttachments struct {
	Context *middleware.Context
	Handler GetDebugAttachmentsHandler
}

func (o *GetDebugAttachments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDebugAttachmentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
