// Code generated by go-swagger; DO NOT EDIT.

package debugattachment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// PatchDebugAttachmentOKCode is the HTTP code returned for type PatchDebugAttachmentOK
const PatchDebugAttachmentOKCode int = 200

/*PatchDebugAttachmentOK Debug attachment modified

swagger:response patchDebugAttachmentOK
*/
type PatchDebugAttachmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugAttachment `json:"body,omitempty"`
}

// NewPatchDebugAttachmentOK creates PatchDebugAttachmentOK with default headers values
func NewPatchDebugAttachmentOK() *PatchDebugAttachmentOK {
	return &PatchDebugAttachmentOK{}
}

// WithPayload adds the payload to the patch debug attachment o k response
func (o *PatchDebugAttachmentOK) WithPayload(payload *models.DebugAttachment) *PatchDebugAttachmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch debug attachment o k response
func (o *PatchDebugAttachmentOK) SetPayload(payload *models.DebugAttachment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchDebugAttachmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchDebugAttachmentBadRequestCode is the HTTP code returned for type PatchDebugAttachmentBadRequest
const PatchDebugAttachmentBadRequestCode int = 400

/*PatchDebugAttachmentBadRequest Bad request

swagger:response patchDebugAttachmentBadRequest
*/
type PatchDebugAttachmentBadRequest struct {
}

// NewPatchDebugAttachmentBadRequest creates PatchDebugAttachmentBadRequest with default headers values
func NewPatchDebugAttachmentBadRequest() *PatchDebugAttachmentBadRequest {
	return &PatchDebugAttachmentBadRequest{}
}

// WriteResponse to the client
func (o *PatchDebugAttachmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PatchDebugAttachmentNotFoundCode is the HTTP code returned for type PatchDebugAttachmentNotFound
const PatchDebugAttachmentNotFoundCode int = 404

/*PatchDebugAttachmentNotFound Not found

swagger:response patchDebugAttachmentNotFound
*/
type PatchDebugAttachmentNotFound struct {
}

// NewPatchDebugAttachmentNotFound creates PatchDebugAttachmentNotFound with default headers values
func NewPatchDebugAttachmentNotFound() *PatchDebugAttachmentNotFound {
	return &PatchDebugAttachmentNotFound{}
}

// WriteResponse to the client
func (o *PatchDebugAttachmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PatchDebugAttachmentConflictCode is the HTTP code returned for type PatchDebugAttachmentConflict
const PatchDebugAttachmentConflictCode int = 409

/*PatchDebugAttachmentConflict Conflict

swagger:response patchDebugAttachmentConflict
*/
type PatchDebugAttachmentConflict struct {
}

// NewPatchDebugAttachmentConflict creates PatchDebugAttachmentConflict with default headers values
func NewPatchDebugAttachmentConflict() *PatchDebugAttachmentConflict {
	return &PatchDebugAttachmentConflict{}
}

// WriteResponse to the client
func (o *PatchDebugAttachmentConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PatchDebugAttachmentUnprocessableEntityCode is the HTTP code returned for type PatchDebugAttachmentUnprocessableEntity
const PatchDebugAttachmentUnprocessableEntityCode int = 422

/*PatchDebugAttachmentUnprocessableEntity Invalid input

swagger:response patchDebugAttachmentUnprocessableEntity
*/
type PatchDebugAttachmentUnprocessableEntity struct {
}

// NewPatchDebugAttachmentUnprocessableEntity creates PatchDebugAttachmentUnprocessableEntity with default headers values
func NewPatchDebugAttachmentUnprocessableEntity() *PatchDebugAttachmentUnprocessableEntity {
	return &PatchDebugAttachmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *PatchDebugAttachmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// PatchDebugAttachmentServiceUnavailableCode is the HTTP code returned for type PatchDebugAttachmentServiceUnavailable
const PatchDebugAttachmentServiceUnavailableCode int = 503

/*PatchDebugAttachmentServiceUnavailable Service Unavailable

swagger:response patchDebugAttachmentServiceUnavailable
*/
type PatchDebugAttachmentServiceUnavailable struct {
}

// NewPatchDebugAttachmentServiceUnavailable creates PatchDebugAttachmentServiceUnavailable with default headers values
func NewPatchDebugAttachmentServiceUnavailable() *PatchDebugAttachmentServiceUnavailable {
	return &PatchDebugAttachmentServiceUnavailable{}
}

// WriteResponse to the client
func (o *PatchDebugAttachmentServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
