// Code generated by go-swagger; DO NOT EDIT.

package debugattchment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// GetDebugAttachmentOKCode is the HTTP code returned for type GetDebugAttachmentOK
const GetDebugAttachmentOKCode int = 200

/*GetDebugAttachmentOK OK

swagger:response getDebugAttachmentOK
*/
type GetDebugAttachmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugAttachment `json:"body,omitempty"`
}

// NewGetDebugAttachmentOK creates GetDebugAttachmentOK with default headers values
func NewGetDebugAttachmentOK() *GetDebugAttachmentOK {
	return &GetDebugAttachmentOK{}
}

// WithPayload adds the payload to the get debug attachment o k response
func (o *GetDebugAttachmentOK) WithPayload(payload *models.DebugAttachment) *GetDebugAttachmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get debug attachment o k response
func (o *GetDebugAttachmentOK) SetPayload(payload *models.DebugAttachment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDebugAttachmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDebugAttachmentBadRequestCode is the HTTP code returned for type GetDebugAttachmentBadRequest
const GetDebugAttachmentBadRequestCode int = 400

/*GetDebugAttachmentBadRequest Invalid ID supplied

swagger:response getDebugAttachmentBadRequest
*/
type GetDebugAttachmentBadRequest struct {
}

// NewGetDebugAttachmentBadRequest creates GetDebugAttachmentBadRequest with default headers values
func NewGetDebugAttachmentBadRequest() *GetDebugAttachmentBadRequest {
	return &GetDebugAttachmentBadRequest{}
}

// WriteResponse to the client
func (o *GetDebugAttachmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDebugAttachmentNotFoundCode is the HTTP code returned for type GetDebugAttachmentNotFound
const GetDebugAttachmentNotFoundCode int = 404

/*GetDebugAttachmentNotFound Debug config not found

swagger:response getDebugAttachmentNotFound
*/
type GetDebugAttachmentNotFound struct {
}

// NewGetDebugAttachmentNotFound creates GetDebugAttachmentNotFound with default headers values
func NewGetDebugAttachmentNotFound() *GetDebugAttachmentNotFound {
	return &GetDebugAttachmentNotFound{}
}

// WriteResponse to the client
func (o *GetDebugAttachmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDebugAttachmentUnprocessableEntityCode is the HTTP code returned for type GetDebugAttachmentUnprocessableEntity
const GetDebugAttachmentUnprocessableEntityCode int = 422

/*GetDebugAttachmentUnprocessableEntity Validation exception

swagger:response getDebugAttachmentUnprocessableEntity
*/
type GetDebugAttachmentUnprocessableEntity struct {
}

// NewGetDebugAttachmentUnprocessableEntity creates GetDebugAttachmentUnprocessableEntity with default headers values
func NewGetDebugAttachmentUnprocessableEntity() *GetDebugAttachmentUnprocessableEntity {
	return &GetDebugAttachmentUnprocessableEntity{}
}

// WriteResponse to the client
func (o *GetDebugAttachmentUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
