// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DebugAttachmentSpec debug attachment spec
// swagger:model DebugAttachmentSpec
type DebugAttachmentSpec struct {

	// attachment
	// Required: true
	Attachment Attachment `json:"attachment"`

	// debugger
	// Required: true
	Debugger *string `json:"debugger"`

	// image
	Image string `json:"image,omitempty"`

	// match request
	MatchRequest bool `json:"match_request,omitempty"`

	// node
	Node string `json:"node,omitempty"`
}

// Validate validates this debug attachment spec
func (m *DebugAttachmentSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttachment(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDebugger(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DebugAttachmentSpec) validateAttachment(formats strfmt.Registry) error {

	return nil
}

func (m *DebugAttachmentSpec) validateDebugger(formats strfmt.Registry) error {

	if err := validate.Required("debugger", "body", m.Debugger); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DebugAttachmentSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DebugAttachmentSpec) UnmarshalBinary(b []byte) error {
	var res DebugAttachmentSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
