// Code generated by protoc-gen-solo-kit. DO NOT EDIT.

package v1

import (
	"sync"
	"time"

	"go.opencensus.io/stats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/tag"

	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/errors"
	"github.com/solo-io/solo-kit/pkg/utils/errutils"
)

var (
	mApiSnapshotIn  = stats.Int64("api.squash.solo.io/snap_emitter/snap_in", "The number of snapshots in", "1")
	mApiSnapshotOut = stats.Int64("api.squash.solo.io/snap_emitter/snap_out", "The number of snapshots out", "1")

	apisnapshotInView = &view.View{
		Name:        "api.squash.solo.io_snap_emitter/snap_in",
		Measure:     mApiSnapshotIn,
		Description: "The number of snapshots updates coming in",
		Aggregation: view.Count(),
		TagKeys:     []tag.Key{},
	}
	apisnapshotOutView = &view.View{
		Name:        "api.squash.solo.io/snap_emitter/snap_out",
		Measure:     mApiSnapshotOut,
		Description: "The number of snapshots updates going out",
		Aggregation: view.Count(),
		TagKeys:     []tag.Key{},
	}
)

func init() {
	view.Register(apisnapshotInView, apisnapshotOutView)
}

type ApiEmitter interface {
	Register() error
	Attachment() AttachmentClient
	Snapshots(watchNamespaces []string, opts clients.WatchOpts) (<-chan *ApiSnapshot, <-chan error, error)
}

func NewApiEmitter(attachmentClient AttachmentClient) ApiEmitter {
	return NewApiEmitterWithEmit(attachmentClient, make(chan struct{}))
}

func NewApiEmitterWithEmit(attachmentClient AttachmentClient, emit <-chan struct{}) ApiEmitter {
	return &apiEmitter{
		attachment: attachmentClient,
		forceEmit:  emit,
	}
}

type apiEmitter struct {
	forceEmit  <-chan struct{}
	attachment AttachmentClient
}

func (c *apiEmitter) Register() error {
	if err := c.attachment.Register(); err != nil {
		return err
	}
	return nil
}

func (c *apiEmitter) Attachment() AttachmentClient {
	return c.attachment
}

func (c *apiEmitter) Snapshots(watchNamespaces []string, opts clients.WatchOpts) (<-chan *ApiSnapshot, <-chan error, error) {
	errs := make(chan error)
	var done sync.WaitGroup
	ctx := opts.Ctx
	/* Create channel for Attachment */
	type attachmentListWithNamespace struct {
		list      AttachmentList
		namespace string
	}
	attachmentChan := make(chan attachmentListWithNamespace)

	for _, namespace := range watchNamespaces {
		/* Setup watch for Attachment */
		attachmentNamespacesChan, attachmentErrs, err := c.attachment.Watch(namespace, opts)
		if err != nil {
			return nil, nil, errors.Wrapf(err, "starting Attachment watch")
		}

		done.Add(1)
		go func(namespace string) {
			defer done.Done()
			errutils.AggregateErrs(ctx, errs, attachmentErrs, namespace+"-attachments")
		}(namespace)

		/* Watch for changes and update snapshot */
		go func(namespace string) {
			for {
				select {
				case <-ctx.Done():
					return
				case attachmentList := <-attachmentNamespacesChan:
					select {
					case <-ctx.Done():
						return
					case attachmentChan <- attachmentListWithNamespace{list: attachmentList, namespace: namespace}:
					}
				}
			}
		}(namespace)
	}

	snapshots := make(chan *ApiSnapshot)
	go func() {
		originalSnapshot := ApiSnapshot{}
		currentSnapshot := originalSnapshot.Clone()
		timer := time.NewTicker(time.Second * 1)
		sync := func() {
			if originalSnapshot.Hash() == currentSnapshot.Hash() {
				return
			}

			stats.Record(ctx, mApiSnapshotOut.M(1))
			originalSnapshot = currentSnapshot.Clone()
			sentSnapshot := currentSnapshot.Clone()
			snapshots <- &sentSnapshot
		}

		/* TODO (yuval-k): figure out how to make this work to avoid a stale snapshot.
		   		// construct the first snapshot from all the configs that are currently there
		   		// that guarantees that the first snapshot contains all the data.
		   		for range watchNamespaces {
		      attachmentNamespacedList := <- attachmentChan
		      currentSnapshot.Attachments.Clear(attachmentNamespacedList.namespace)
		      attachmentList := attachmentNamespacedList.list
		   	currentSnapshot.Attachments.Add(attachmentList...)
		   		}
		*/

		for {
			record := func() { stats.Record(ctx, mApiSnapshotIn.M(1)) }

			select {
			case <-timer.C:
				sync()
			case <-ctx.Done():
				close(snapshots)
				done.Wait()
				close(errs)
				return
			case <-c.forceEmit:
				sentSnapshot := currentSnapshot.Clone()
				snapshots <- &sentSnapshot
			case attachmentNamespacedList := <-attachmentChan:
				record()

				namespace := attachmentNamespacedList.namespace
				attachmentList := attachmentNamespacedList.list

				currentSnapshot.Attachments.Clear(namespace)
				currentSnapshot.Attachments.Add(attachmentList...)
			}
		}
	}()
	return snapshots, errs, nil
}
