// Code generated by protoc-gen-solo-kit. DO NOT EDIT.

package v1

import (
	"context"
	"os"
	"path/filepath"
	"time"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/factory"
	kuberc "github.com/solo-io/solo-kit/pkg/api/v1/clients/kube"
	"github.com/solo-io/solo-kit/pkg/utils/log"
	"github.com/solo-io/solo-kit/test/helpers"
	"github.com/solo-io/solo-kit/test/setup"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

var _ = Describe("V1Emitter", func() {
	if os.Getenv("RUN_KUBE_TESTS") != "1" {
		log.Printf("This test creates kubernetes resources and is disabled by default. To enable, set RUN_KUBE_TESTS=1 in your env.")
		return
	}
	var (
		namespace1            string
		namespace2            string
		cfg                   *rest.Config
		emitter               ApiEmitter
		debugAttachmentClient DebugAttachmentClient
	)

	BeforeEach(func() {
		namespace1 = helpers.RandString(8)
		namespace2 = helpers.RandString(8)
		err := setup.SetupKubeForTest(namespace1)
		Expect(err).NotTo(HaveOccurred())
		err = setup.SetupKubeForTest(namespace2)
		kubeconfigPath := filepath.Join(os.Getenv("HOME"), ".kube", "config")
		cfg, err = clientcmd.BuildConfigFromFlags("", kubeconfigPath)
		Expect(err).NotTo(HaveOccurred())

		cache := kuberc.NewKubeCache()
		// DebugAttachment Constructor
		debugAttachmentClientFactory := &factory.KubeResourceClientFactory{
			Crd:         DebugAttachmentCrd,
			Cfg:         cfg,
			SharedCache: cache,
		}
		debugAttachmentClient, err = NewDebugAttachmentClient(debugAttachmentClientFactory)
		Expect(err).NotTo(HaveOccurred())
		emitter = NewApiEmitter(debugAttachmentClient)
	})
	AfterEach(func() {
		setup.TeardownKube(namespace1)
		setup.TeardownKube(namespace2)
	})
	It("tracks snapshots on changes to any resource", func() {
		ctx := context.Background()
		err := emitter.Register()
		Expect(err).NotTo(HaveOccurred())

		snapshots, errs, err := emitter.Snapshots([]string{namespace1, namespace2}, clients.WatchOpts{
			Ctx:         ctx,
			RefreshRate: time.Second,
		})
		Expect(err).NotTo(HaveOccurred())

		var snap *ApiSnapshot

		/*
			DebugAttachment
		*/

		assertSnapshotDebugattachments := func(expectDebugattachments DebugAttachmentList, unexpectDebugattachments DebugAttachmentList) {
		drain:
			for {
				select {
				case snap = <-snapshots:
					for _, expected := range expectDebugattachments {
						if _, err := snap.Debugattachments.List().Find(expected.Metadata.Ref().Strings()); err != nil {
							continue drain
						}
					}
					for _, unexpected := range unexpectDebugattachments {
						if _, err := snap.Debugattachments.List().Find(unexpected.Metadata.Ref().Strings()); err == nil {
							continue drain
						}
					}
					break drain
				case err := <-errs:
					Expect(err).NotTo(HaveOccurred())
				case <-time.After(time.Second * 10):
					nsList1, _ := debugAttachmentClient.List(namespace1, clients.ListOpts{})
					nsList2, _ := debugAttachmentClient.List(namespace2, clients.ListOpts{})
					combined := nsList1.ByNamespace()
					combined.Add(nsList2...)
					Fail("expected final snapshot before 10 seconds. expected " + log.Sprintf("%v", combined))
				}
			}
		}

		debugAttachment1a, err := debugAttachmentClient.Write(NewDebugAttachment(namespace1, "angela"), clients.WriteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())
		debugAttachment1b, err := debugAttachmentClient.Write(NewDebugAttachment(namespace2, "angela"), clients.WriteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())

		assertSnapshotDebugattachments(DebugAttachmentList{debugAttachment1a, debugAttachment1b}, nil)

		debugAttachment2a, err := debugAttachmentClient.Write(NewDebugAttachment(namespace1, "bob"), clients.WriteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())
		debugAttachment2b, err := debugAttachmentClient.Write(NewDebugAttachment(namespace2, "bob"), clients.WriteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())

		assertSnapshotDebugattachments(DebugAttachmentList{debugAttachment1a, debugAttachment1b, debugAttachment2a, debugAttachment2b}, nil)

		err = debugAttachmentClient.Delete(debugAttachment2a.Metadata.Namespace, debugAttachment2a.Metadata.Name, clients.DeleteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())
		err = debugAttachmentClient.Delete(debugAttachment2b.Metadata.Namespace, debugAttachment2b.Metadata.Name, clients.DeleteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())

		assertSnapshotDebugattachments(DebugAttachmentList{debugAttachment1a, debugAttachment1b}, DebugAttachmentList{debugAttachment2a, debugAttachment2b})

		err = debugAttachmentClient.Delete(debugAttachment1a.Metadata.Namespace, debugAttachment1a.Metadata.Name, clients.DeleteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())
		err = debugAttachmentClient.Delete(debugAttachment1b.Metadata.Namespace, debugAttachment1b.Metadata.Name, clients.DeleteOpts{Ctx: ctx})
		Expect(err).NotTo(HaveOccurred())

		assertSnapshotDebugattachments(nil, DebugAttachmentList{debugAttachment1a, debugAttachment1b, debugAttachment2a, debugAttachment2b})
	})
})
