// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: attachment.proto

package v1 // import "github.com/solo-io/squash/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// @solo-kit:resource.short_name=att
// @solo-kit:resource.plural_name=attachments
// @solo-kit:resource.resource_groups=api.squash.solo.io
//
// Attachments store the information needed for squash to coordinate a debugging session
type Attachment struct {
	Debugger             string        `protobuf:"bytes,1,opt,name=debugger,proto3" json:"debugger,omitempty"`
	Image                string        `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ProcessName          string        `protobuf:"bytes,3,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Node                 string        `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	MatchRequest         bool          `protobuf:"varint,5,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	Metadata             core.Metadata `protobuf:"bytes,6,opt,name=metadata" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_attachment_586092936941ad95, []int{0}
}
func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (dst *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(dst, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetDebugger() string {
	if m != nil {
		return m.Debugger
	}
	return ""
}

func (m *Attachment) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Attachment) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *Attachment) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Attachment) GetMatchRequest() bool {
	if m != nil {
		return m.MatchRequest
	}
	return false
}

func (m *Attachment) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func init() {
	proto.RegisterType((*Attachment)(nil), "squash.solo.io.Attachment")
}
func (this *Attachment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Attachment)
	if !ok {
		that2, ok := that.(Attachment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Debugger != that1.Debugger {
		return false
	}
	if this.Image != that1.Image {
		return false
	}
	if this.ProcessName != that1.ProcessName {
		return false
	}
	if this.Node != that1.Node {
		return false
	}
	if this.MatchRequest != that1.MatchRequest {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("attachment.proto", fileDescriptor_attachment_586092936941ad95) }

var fileDescriptor_attachment_586092936941ad95 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x3f, 0x7f, 0xb4, 0x55, 0x71, 0x0b, 0x42, 0x56, 0x85, 0xac, 0x0e, 0x50, 0x7e, 0x86,
	0x0a, 0x81, 0xad, 0xc2, 0xc2, 0x4a, 0x77, 0x18, 0x32, 0xb2, 0x54, 0x4e, 0x72, 0x70, 0xac, 0xe2,
	0x9c, 0xd4, 0x76, 0xb8, 0x26, 0x2e, 0x85, 0x0b, 0x60, 0x66, 0xe0, 0x4a, 0x50, 0x9d, 0x34, 0x13,
	0x03, 0x53, 0xce, 0x79, 0x9f, 0xf7, 0x48, 0xf1, 0x43, 0x8f, 0x54, 0x08, 0x2a, 0x2b, 0x2c, 0x94,
	0x41, 0x54, 0x0e, 0x03, 0xb2, 0x43, 0xbf, 0xa9, 0x95, 0x2f, 0x84, 0xc7, 0x57, 0x14, 0x06, 0xa7,
	0x13, 0x8d, 0x1a, 0x23, 0x92, 0xdb, 0xa9, 0x69, 0x4d, 0x17, 0xda, 0x84, 0xa2, 0x4e, 0x45, 0x86,
	0x56, 0x6e, 0x9b, 0x37, 0x06, 0x9b, 0xef, 0xda, 0x04, 0xa9, 0x2a, 0x23, 0xdf, 0x16, 0xd2, 0x42,
	0x50, 0xb9, 0x0a, 0xaa, 0x3d, 0xb9, 0xfe, 0xc3, 0x89, 0x83, 0x97, 0xa6, 0x7d, 0xfe, 0x49, 0x28,
	0x7d, 0xe8, 0xfe, 0x8d, 0x4d, 0xe9, 0x30, 0x87, 0xb4, 0xd6, 0x1a, 0x1c, 0x27, 0x33, 0x32, 0xdf,
	0x4f, 0xba, 0x9d, 0x4d, 0x68, 0xdf, 0x58, 0xa5, 0x81, 0xff, 0x8f, 0xa0, 0x59, 0xd8, 0x19, 0x1d,
	0x57, 0x0e, 0x33, 0xf0, 0x7e, 0x55, 0x2a, 0x0b, 0x7c, 0x2f, 0xc2, 0x51, 0x9b, 0x3d, 0x29, 0x0b,
	0x8c, 0xd1, 0x5e, 0x89, 0x39, 0xf0, 0x5e, 0x44, 0x71, 0x66, 0x17, 0xf4, 0xc0, 0xaa, 0x90, 0x15,
	0x2b, 0x07, 0x9b, 0x1a, 0x7c, 0xe0, 0xfd, 0x19, 0x99, 0x0f, 0x93, 0x71, 0x0c, 0x93, 0x26, 0x63,
	0xf7, 0x74, 0xb8, 0x7b, 0x1c, 0x1f, 0xcc, 0xc8, 0x7c, 0x74, 0x7b, 0x2c, 0x32, 0x74, 0xb0, 0x93,
	0x26, 0x1e, 0x5b, 0xba, 0xec, 0x7d, 0x7c, 0x9d, 0xfe, 0x4b, 0xba, 0xf6, 0xf2, 0xea, 0xfd, 0xfb,
	0x84, 0x3c, 0x5f, 0xfe, 0xa6, 0x22, 0x6a, 0x97, 0xd5, 0x5a, 0xb7, 0x32, 0xd2, 0x41, 0x34, 0x71,
	0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x75, 0x30, 0x61, 0xd9, 0xa4, 0x01, 0x00, 0x00,
}
