// Code generated by protoc-gen-solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/factory"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/errors"
)

type AttachmentClient interface {
	BaseClient() clients.ResourceClient
	Register() error
	Read(namespace, name string, opts clients.ReadOpts) (*Attachment, error)
	Write(resource *Attachment, opts clients.WriteOpts) (*Attachment, error)
	Delete(namespace, name string, opts clients.DeleteOpts) error
	List(namespace string, opts clients.ListOpts) (AttachmentList, error)
	Watch(namespace string, opts clients.WatchOpts) (<-chan AttachmentList, <-chan error, error)
}

type attachmentClient struct {
	rc clients.ResourceClient
}

func NewAttachmentClient(rcFactory factory.ResourceClientFactory) (AttachmentClient, error) {
	return NewAttachmentClientWithToken(rcFactory, "")
}

func NewAttachmentClientWithToken(rcFactory factory.ResourceClientFactory, token string) (AttachmentClient, error) {
	rc, err := rcFactory.NewResourceClient(factory.NewResourceClientParams{
		ResourceType: &Attachment{},
		Token:        token,
	})
	if err != nil {
		return nil, errors.Wrapf(err, "creating base Attachment resource client")
	}
	return &attachmentClient{
		rc: rc,
	}, nil
}

func (client *attachmentClient) BaseClient() clients.ResourceClient {
	return client.rc
}

func (client *attachmentClient) Register() error {
	return client.rc.Register()
}

func (client *attachmentClient) Read(namespace, name string, opts clients.ReadOpts) (*Attachment, error) {
	opts = opts.WithDefaults()
	resource, err := client.rc.Read(namespace, name, opts)
	if err != nil {
		return nil, err
	}
	return resource.(*Attachment), nil
}

func (client *attachmentClient) Write(attachment *Attachment, opts clients.WriteOpts) (*Attachment, error) {
	opts = opts.WithDefaults()
	resource, err := client.rc.Write(attachment, opts)
	if err != nil {
		return nil, err
	}
	return resource.(*Attachment), nil
}

func (client *attachmentClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	opts = opts.WithDefaults()
	return client.rc.Delete(namespace, name, opts)
}

func (client *attachmentClient) List(namespace string, opts clients.ListOpts) (AttachmentList, error) {
	opts = opts.WithDefaults()
	resourceList, err := client.rc.List(namespace, opts)
	if err != nil {
		return nil, err
	}
	return convertToAttachment(resourceList), nil
}

func (client *attachmentClient) Watch(namespace string, opts clients.WatchOpts) (<-chan AttachmentList, <-chan error, error) {
	opts = opts.WithDefaults()
	resourcesChan, errs, initErr := client.rc.Watch(namespace, opts)
	if initErr != nil {
		return nil, nil, initErr
	}
	attachmentsChan := make(chan AttachmentList)
	go func() {
		for {
			select {
			case resourceList := <-resourcesChan:
				attachmentsChan <- convertToAttachment(resourceList)
			case <-opts.Ctx.Done():
				close(attachmentsChan)
				return
			}
		}
	}()
	return attachmentsChan, errs, nil
}

func convertToAttachment(resources resources.ResourceList) AttachmentList {
	var attachmentList AttachmentList
	for _, resource := range resources {
		attachmentList = append(attachmentList, resource.(*Attachment))
	}
	return attachmentList
}
