// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: debug_attachment.proto

package v1 // import "github.com/solo-io/squash/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// @solo-kit:resource.short_name=debatt
// @solo-kit:resource.plural_name=debugattachments
// @solo-kit:resource.resource_groups=api.squash.solo.io
//
// Attachments store the information needed for squash to coordinate a debugging session
type DebugAttachment struct {
	Metadata             core.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata"`
	Status               core.Status   `protobuf:"bytes,2,opt,name=status" json:"status" testdiff:"ignore"`
	Attachment           string        `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	Debugger             string        `protobuf:"bytes,4,opt,name=debugger,proto3" json:"debugger,omitempty"`
	Image                string        `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	ProcessName          string        `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Node                 string        `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`
	MatchRequest         bool          `protobuf:"varint,8,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	DebugServerAddress   string        `protobuf:"bytes,9,opt,name=debug_server_address,json=debugServerAddress,proto3" json:"debug_server_address,omitempty"`
	State                string        `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Pod                  string        `protobuf:"bytes,11,opt,name=pod,proto3" json:"pod,omitempty"`
	Container            string        `protobuf:"bytes,12,opt,name=container,proto3" json:"container,omitempty"`
	DebugNamespace       string        `protobuf:"bytes,13,opt,name=debug_namespace,json=debugNamespace,proto3" json:"debug_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DebugAttachment) Reset()         { *m = DebugAttachment{} }
func (m *DebugAttachment) String() string { return proto.CompactTextString(m) }
func (*DebugAttachment) ProtoMessage()    {}
func (*DebugAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_debug_attachment_6d65f07f05e101e3, []int{0}
}
func (m *DebugAttachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugAttachment.Unmarshal(m, b)
}
func (m *DebugAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugAttachment.Marshal(b, m, deterministic)
}
func (dst *DebugAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugAttachment.Merge(dst, src)
}
func (m *DebugAttachment) XXX_Size() int {
	return xxx_messageInfo_DebugAttachment.Size(m)
}
func (m *DebugAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_DebugAttachment proto.InternalMessageInfo

func (m *DebugAttachment) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *DebugAttachment) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *DebugAttachment) GetAttachment() string {
	if m != nil {
		return m.Attachment
	}
	return ""
}

func (m *DebugAttachment) GetDebugger() string {
	if m != nil {
		return m.Debugger
	}
	return ""
}

func (m *DebugAttachment) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DebugAttachment) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *DebugAttachment) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *DebugAttachment) GetMatchRequest() bool {
	if m != nil {
		return m.MatchRequest
	}
	return false
}

func (m *DebugAttachment) GetDebugServerAddress() string {
	if m != nil {
		return m.DebugServerAddress
	}
	return ""
}

func (m *DebugAttachment) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *DebugAttachment) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *DebugAttachment) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *DebugAttachment) GetDebugNamespace() string {
	if m != nil {
		return m.DebugNamespace
	}
	return ""
}

func init() {
	proto.RegisterType((*DebugAttachment)(nil), "squash.solo.io.DebugAttachment")
}
func (this *DebugAttachment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DebugAttachment)
	if !ok {
		that2, ok := that.(DebugAttachment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if this.Attachment != that1.Attachment {
		return false
	}
	if this.Debugger != that1.Debugger {
		return false
	}
	if this.Image != that1.Image {
		return false
	}
	if this.ProcessName != that1.ProcessName {
		return false
	}
	if this.Node != that1.Node {
		return false
	}
	if this.MatchRequest != that1.MatchRequest {
		return false
	}
	if this.DebugServerAddress != that1.DebugServerAddress {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if this.Pod != that1.Pod {
		return false
	}
	if this.Container != that1.Container {
		return false
	}
	if this.DebugNamespace != that1.DebugNamespace {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("debug_attachment.proto", fileDescriptor_debug_attachment_6d65f07f05e101e3)
}

var fileDescriptor_debug_attachment_6d65f07f05e101e3 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x31, 0x49, 0x43, 0x32, 0x49, 0x5b, 0x58, 0x45, 0xd5, 0x12, 0xa1, 0x36, 0x04, 0x24,
	0x22, 0x04, 0x36, 0x85, 0x0b, 0xe2, 0xd6, 0x08, 0x89, 0x13, 0x3d, 0xb8, 0x37, 0x2e, 0xd6, 0xc6,
	0x9e, 0xac, 0x57, 0xc5, 0x5e, 0x77, 0x77, 0xdd, 0x67, 0xe2, 0x51, 0x78, 0x8a, 0x1e, 0xe0, 0x0d,
	0x78, 0x02, 0xb4, 0xb3, 0x4e, 0x0a, 0x52, 0x0f, 0x3d, 0x65, 0xe6, 0xff, 0xe6, 0x8f, 0x67, 0xec,
	0x1f, 0x8e, 0x0a, 0x5c, 0xb7, 0x32, 0x13, 0xce, 0x89, 0xbc, 0xac, 0xb0, 0x76, 0x71, 0x63, 0xb4,
	0xd3, 0xec, 0xc0, 0x5e, 0xb5, 0xc2, 0x96, 0xb1, 0xd5, 0xdf, 0x75, 0xac, 0xf4, 0x6c, 0x2a, 0xb5,
	0xd4, 0x84, 0x12, 0x5f, 0x85, 0xa9, 0xd9, 0xa9, 0x54, 0xae, 0x6c, 0xd7, 0x71, 0xae, 0xab, 0xc4,
	0x4f, 0xbe, 0x55, 0x3a, 0xfc, 0x5e, 0x2a, 0x97, 0x88, 0x46, 0x25, 0xd7, 0xa7, 0x49, 0x85, 0x4e,
	0x14, 0xc2, 0x89, 0xce, 0x92, 0xdc, 0xc3, 0x62, 0x9d, 0x70, 0xad, 0xed, 0x0c, 0x6f, 0xee, 0x61,
	0x30, 0xb8, 0x09, 0xd3, 0x8b, 0xdf, 0x3d, 0x38, 0xfc, 0xec, 0x4f, 0x3a, 0xdb, 0x5d, 0xc4, 0x3e,
	0xc2, 0x70, 0xbb, 0x04, 0x8f, 0xe6, 0xd1, 0x72, 0xfc, 0xfe, 0x28, 0xce, 0xb5, 0xc1, 0xed, 0x71,
	0xf1, 0xd7, 0x8e, 0xae, 0xfa, 0x3f, 0x6f, 0x4e, 0x1e, 0xa4, 0xbb, 0x69, 0xf6, 0x05, 0x06, 0x61,
	0x17, 0xfe, 0x90, 0x7c, 0xd3, 0xff, 0x7d, 0x17, 0xc4, 0x56, 0x4f, 0xbd, 0xeb, 0xcf, 0xcd, 0xc9,
	0x13, 0x87, 0xd6, 0x15, 0x6a, 0xb3, 0xf9, 0xb4, 0x50, 0xb2, 0xd6, 0x06, 0x17, 0x69, 0x67, 0x67,
	0xc7, 0x00, 0xb7, 0xaf, 0x98, 0xf7, 0xe6, 0xd1, 0x72, 0x94, 0xfe, 0xa3, 0xb0, 0x19, 0x0c, 0xe9,
	0x43, 0x48, 0x34, 0xbc, 0x4f, 0x74, 0xd7, 0xb3, 0x29, 0xec, 0xa9, 0x4a, 0x48, 0xe4, 0x7b, 0x04,
	0x42, 0xc3, 0x9e, 0xc3, 0xa4, 0x31, 0x3a, 0x47, 0x6b, 0xb3, 0x5a, 0x54, 0xc8, 0x07, 0x04, 0xc7,
	0x9d, 0x76, 0x2e, 0x2a, 0x64, 0x0c, 0xfa, 0xb5, 0x2e, 0x90, 0x3f, 0x22, 0x44, 0x35, 0x7b, 0x01,
	0xfb, 0x95, 0x70, 0x79, 0x99, 0x19, 0xbc, 0x6a, 0xd1, 0x3a, 0x3e, 0x9c, 0x47, 0xcb, 0x61, 0x3a,
	0x21, 0x31, 0x0d, 0x1a, 0x7b, 0x07, 0xd3, 0x10, 0x0b, 0x8b, 0xe6, 0x1a, 0x4d, 0x26, 0x8a, 0xc2,
	0xa0, 0xb5, 0x7c, 0x44, 0x7f, 0xc4, 0x88, 0x5d, 0x10, 0x3a, 0x0b, 0xc4, 0xef, 0xe8, 0x2f, 0x45,
	0x0e, 0x61, 0x47, 0x6a, 0xd8, 0x63, 0xe8, 0x35, 0xba, 0xe0, 0x63, 0xd2, 0x7c, 0xc9, 0x9e, 0xc1,
	0x28, 0xd7, 0xb5, 0x13, 0xaa, 0x46, 0xc3, 0x27, 0xa4, 0xdf, 0x0a, 0xec, 0x15, 0x1c, 0x86, 0xe7,
	0xfa, 0x8b, 0x6c, 0x23, 0x72, 0xe4, 0xfb, 0x34, 0x73, 0x40, 0xf2, 0xf9, 0x56, 0x5d, 0xbd, 0xfe,
	0xf1, 0xeb, 0x38, 0xfa, 0xf6, 0xf2, 0xae, 0x64, 0x50, 0x6c, 0x93, 0xe6, 0x52, 0x76, 0xd9, 0x58,
	0x0f, 0x28, 0x18, 0x1f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x6e, 0x85, 0xb7, 0xea, 0x02,
	0x00, 0x00,
}
