// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: debug_attachment.proto

package v1 // import "github.com/solo-io/squash/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DebugAttachment_State int32

const (
	// Newly created DebugAttachments have state RequestingAttachment
	DebugAttachment_RequestingAttachment DebugAttachment_State = 0
	// When the event loop begins fullfilling an attachment request it sets
	// DebugAttachments state to PendingAttachment
	DebugAttachment_PendingAttachment DebugAttachment_State = 1
	// When squash client successfully attaches, it sets state to Attached
	DebugAttachment_Attached DebugAttachment_State = 2
	// Indicates that user has requested an attachment be removed
	DebugAttachment_RequestingDelete DebugAttachment_State = 3
	// When the event loop begins fullfilling a delete request it sets this
	// status and triggers a cleanup routine
	// When the cleanup routine completes, it deletes the CRD
	DebugAttachment_PendingDelete DebugAttachment_State = 4
)

var DebugAttachment_State_name = map[int32]string{
	0: "RequestingAttachment",
	1: "PendingAttachment",
	2: "Attached",
	3: "RequestingDelete",
	4: "PendingDelete",
}
var DebugAttachment_State_value = map[string]int32{
	"RequestingAttachment": 0,
	"PendingAttachment":    1,
	"Attached":             2,
	"RequestingDelete":     3,
	"PendingDelete":        4,
}

func (x DebugAttachment_State) String() string {
	return proto.EnumName(DebugAttachment_State_name, int32(x))
}
func (DebugAttachment_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_debug_attachment_169d0a66f5857f92, []int{0, 0}
}

//
// @solo-kit:resource.short_name=debatt
// @solo-kit:resource.plural_name=debugattachments
// @solo-kit:resource.resource_groups=api.squash.solo.io
//
// Attachments store the information needed for squash to coordinate a debugging session
type DebugAttachment struct {
	Metadata             core.Metadata         `protobuf:"bytes,1,opt,name=metadata" json:"metadata"`
	Status               core.Status           `protobuf:"bytes,2,opt,name=status" json:"status" testdiff:"ignore"`
	Attachment           string                `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	Debugger             string                `protobuf:"bytes,4,opt,name=debugger,proto3" json:"debugger,omitempty"`
	Image                string                `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	ProcessName          string                `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Node                 string                `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`
	MatchRequest         bool                  `protobuf:"varint,8,opt,name=match_request,json=matchRequest,proto3" json:"match_request,omitempty"`
	DebugServerAddress   string                `protobuf:"bytes,9,opt,name=debug_server_address,json=debugServerAddress,proto3" json:"debug_server_address,omitempty"`
	State                DebugAttachment_State `protobuf:"varint,10,opt,name=state,proto3,enum=squash.solo.io.DebugAttachment_State" json:"state,omitempty"`
	Pod                  string                `protobuf:"bytes,11,opt,name=pod,proto3" json:"pod,omitempty"`
	Container            string                `protobuf:"bytes,12,opt,name=container,proto3" json:"container,omitempty"`
	DebugNamespace       string                `protobuf:"bytes,13,opt,name=debug_namespace,json=debugNamespace,proto3" json:"debug_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DebugAttachment) Reset()         { *m = DebugAttachment{} }
func (m *DebugAttachment) String() string { return proto.CompactTextString(m) }
func (*DebugAttachment) ProtoMessage()    {}
func (*DebugAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_debug_attachment_169d0a66f5857f92, []int{0}
}
func (m *DebugAttachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugAttachment.Unmarshal(m, b)
}
func (m *DebugAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugAttachment.Marshal(b, m, deterministic)
}
func (dst *DebugAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugAttachment.Merge(dst, src)
}
func (m *DebugAttachment) XXX_Size() int {
	return xxx_messageInfo_DebugAttachment.Size(m)
}
func (m *DebugAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_DebugAttachment proto.InternalMessageInfo

func (m *DebugAttachment) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *DebugAttachment) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *DebugAttachment) GetAttachment() string {
	if m != nil {
		return m.Attachment
	}
	return ""
}

func (m *DebugAttachment) GetDebugger() string {
	if m != nil {
		return m.Debugger
	}
	return ""
}

func (m *DebugAttachment) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DebugAttachment) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *DebugAttachment) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *DebugAttachment) GetMatchRequest() bool {
	if m != nil {
		return m.MatchRequest
	}
	return false
}

func (m *DebugAttachment) GetDebugServerAddress() string {
	if m != nil {
		return m.DebugServerAddress
	}
	return ""
}

func (m *DebugAttachment) GetState() DebugAttachment_State {
	if m != nil {
		return m.State
	}
	return DebugAttachment_RequestingAttachment
}

func (m *DebugAttachment) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *DebugAttachment) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *DebugAttachment) GetDebugNamespace() string {
	if m != nil {
		return m.DebugNamespace
	}
	return ""
}

func init() {
	proto.RegisterType((*DebugAttachment)(nil), "squash.solo.io.DebugAttachment")
	proto.RegisterEnum("squash.solo.io.DebugAttachment_State", DebugAttachment_State_name, DebugAttachment_State_value)
}
func (this *DebugAttachment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DebugAttachment)
	if !ok {
		that2, ok := that.(DebugAttachment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if this.Attachment != that1.Attachment {
		return false
	}
	if this.Debugger != that1.Debugger {
		return false
	}
	if this.Image != that1.Image {
		return false
	}
	if this.ProcessName != that1.ProcessName {
		return false
	}
	if this.Node != that1.Node {
		return false
	}
	if this.MatchRequest != that1.MatchRequest {
		return false
	}
	if this.DebugServerAddress != that1.DebugServerAddress {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if this.Pod != that1.Pod {
		return false
	}
	if this.Container != that1.Container {
		return false
	}
	if this.DebugNamespace != that1.DebugNamespace {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("debug_attachment.proto", fileDescriptor_debug_attachment_169d0a66f5857f92)
}

var fileDescriptor_debug_attachment_169d0a66f5857f92 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xe6, 0x0f, 0xc9, 0xe4, 0x4f, 0x93, 0x95, 0xa9, 0x96, 0x08, 0xb5, 0x21, 0x80,
	0x88, 0x10, 0xd8, 0xb4, 0x5c, 0x10, 0x9c, 0x1a, 0x55, 0xe2, 0x44, 0x85, 0xdc, 0x1b, 0x97, 0x68,
	0x63, 0x4f, 0x1c, 0xab, 0xb5, 0xd7, 0xdd, 0x5d, 0xf7, 0x99, 0x78, 0x14, 0x9e, 0xa2, 0x07, 0x1e,
	0x81, 0x2b, 0x17, 0xe4, 0x59, 0x27, 0x69, 0x50, 0x0f, 0x3d, 0x79, 0xf7, 0xfb, 0xe6, 0xb7, 0x9e,
	0x6f, 0x77, 0xe0, 0x30, 0xc2, 0x45, 0x11, 0xcf, 0x85, 0x31, 0x22, 0x5c, 0xa5, 0x98, 0x19, 0x2f,
	0x57, 0xd2, 0x48, 0xd6, 0xd7, 0x37, 0x85, 0xd0, 0x2b, 0x4f, 0xcb, 0x6b, 0xe9, 0x25, 0x72, 0xe4,
	0xc6, 0x32, 0x96, 0x64, 0xf9, 0xe5, 0xca, 0x56, 0x8d, 0x4e, 0xe2, 0xc4, 0xac, 0x8a, 0x85, 0x17,
	0xca, 0xd4, 0x2f, 0x2b, 0xdf, 0x27, 0xd2, 0x7e, 0xaf, 0x12, 0xe3, 0x8b, 0x3c, 0xf1, 0x6f, 0x4f,
	0xfc, 0x14, 0x8d, 0x88, 0x84, 0x11, 0x15, 0xe2, 0x3f, 0x02, 0xd1, 0x46, 0x98, 0x42, 0x57, 0xc0,
	0xbb, 0x47, 0x00, 0x0a, 0x97, 0xb6, 0x7a, 0xf2, 0xb7, 0x0e, 0x07, 0xe7, 0x65, 0xa4, 0xb3, 0x4d,
	0x22, 0xf6, 0x09, 0x5a, 0xeb, 0x26, 0xb8, 0x33, 0x76, 0xa6, 0x9d, 0xd3, 0x43, 0x2f, 0x94, 0x0a,
	0xd7, 0xe1, 0xbc, 0x6f, 0x95, 0x3b, 0xab, 0xff, 0xba, 0x3b, 0xde, 0x0b, 0x36, 0xd5, 0xec, 0x2b,
	0x34, 0x6d, 0x2f, 0x7c, 0x9f, 0x38, 0x77, 0x97, 0xbb, 0x24, 0x6f, 0xf6, 0xac, 0xa4, 0xfe, 0xdc,
	0x1d, 0x0f, 0x0d, 0x6a, 0x13, 0x25, 0xcb, 0xe5, 0xe7, 0x49, 0x12, 0x67, 0x52, 0xe1, 0x24, 0xa8,
	0x70, 0x76, 0x04, 0xb0, 0xbd, 0x62, 0x5e, 0x1b, 0x3b, 0xd3, 0x76, 0x70, 0x4f, 0x61, 0x23, 0x68,
	0xd1, 0x43, 0xc4, 0xa8, 0x78, 0x9d, 0xdc, 0xcd, 0x9e, 0xb9, 0xd0, 0x48, 0x52, 0x11, 0x23, 0x6f,
	0x90, 0x61, 0x37, 0xec, 0x05, 0x74, 0x73, 0x25, 0x43, 0xd4, 0x7a, 0x9e, 0x89, 0x14, 0x79, 0x93,
	0xcc, 0x4e, 0xa5, 0x5d, 0x88, 0x14, 0x19, 0x83, 0x7a, 0x26, 0x23, 0xe4, 0x4f, 0xc8, 0xa2, 0x35,
	0x7b, 0x09, 0xbd, 0x54, 0x98, 0x70, 0x35, 0x57, 0x78, 0x53, 0xa0, 0x36, 0xbc, 0x35, 0x76, 0xa6,
	0xad, 0xa0, 0x4b, 0x62, 0x60, 0x35, 0xf6, 0x01, 0x5c, 0x3b, 0x16, 0x1a, 0xd5, 0x2d, 0xaa, 0xb9,
	0x88, 0x22, 0x85, 0x5a, 0xf3, 0x36, 0x1d, 0xc4, 0xc8, 0xbb, 0x24, 0xeb, 0xcc, 0x3a, 0xec, 0x0b,
	0x34, 0xca, 0xa4, 0xc8, 0x61, 0xec, 0x4c, 0xfb, 0xa7, 0xaf, 0xbd, 0xdd, 0xf1, 0xf1, 0xfe, 0x7b,
	0x12, 0xba, 0x39, 0x0c, 0x2c, 0xc3, 0x06, 0x50, 0xcb, 0x65, 0xc4, 0x3b, 0x74, 0x7a, 0xb9, 0x64,
	0xcf, 0xa1, 0x1d, 0xca, 0xcc, 0x88, 0x24, 0x43, 0xc5, 0xbb, 0xa4, 0x6f, 0x05, 0xf6, 0x06, 0x0e,
	0x6c, 0x7b, 0x65, 0x70, 0x9d, 0x8b, 0x10, 0x79, 0x8f, 0x6a, 0xfa, 0x24, 0x5f, 0xac, 0xd5, 0x89,
	0x84, 0x06, 0xfd, 0x88, 0x71, 0x70, 0xab, 0x6c, 0x49, 0x76, 0xaf, 0x8d, 0xc1, 0x1e, 0x7b, 0x0a,
	0xc3, 0xef, 0x98, 0x45, 0xbb, 0xb2, 0xc3, 0xba, 0xd0, 0xb2, 0x7b, 0x8c, 0x06, 0xfb, 0xcc, 0x85,
	0xc1, 0x16, 0x3f, 0xc7, 0x6b, 0x34, 0x38, 0xa8, 0xb1, 0x21, 0xf4, 0x2a, 0xb4, 0x92, 0xea, 0xb3,
	0xb7, 0x3f, 0x7f, 0x1f, 0x39, 0x3f, 0x5e, 0x3d, 0x34, 0xb1, 0x74, 0x1f, 0x7e, 0x7e, 0x15, 0x57,
	0x33, 0xbb, 0x68, 0xd2, 0xc0, 0x7e, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xa7, 0xf7, 0x3e,
	0x82, 0x03, 0x00, 0x00,
}
