package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/solo-io/squash/pkg/models"
)

// AddDebugConfigReader is a Reader for the AddDebugConfig structure.
type AddDebugConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddDebugConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddDebugConfigCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddDebugConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAddDebugConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewAddDebugConfigUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewAddDebugConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddDebugConfigCreated creates a AddDebugConfigCreated with default headers values
func NewAddDebugConfigCreated() *AddDebugConfigCreated {
	return &AddDebugConfigCreated{}
}

/*AddDebugConfigCreated handles this case with default header values.

Debug config created
*/
type AddDebugConfigCreated struct {
	Payload *models.DebugConfig
}

func (o *AddDebugConfigCreated) Error() string {
	return fmt.Sprintf("[POST /debugconfig][%d] addDebugConfigCreated  %+v", 201, o.Payload)
}

func (o *AddDebugConfigCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DebugConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddDebugConfigBadRequest creates a AddDebugConfigBadRequest with default headers values
func NewAddDebugConfigBadRequest() *AddDebugConfigBadRequest {
	return &AddDebugConfigBadRequest{}
}

/*AddDebugConfigBadRequest handles this case with default header values.

Bad request
*/
type AddDebugConfigBadRequest struct {
}

func (o *AddDebugConfigBadRequest) Error() string {
	return fmt.Sprintf("[POST /debugconfig][%d] addDebugConfigBadRequest ", 400)
}

func (o *AddDebugConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddDebugConfigNotFound creates a AddDebugConfigNotFound with default headers values
func NewAddDebugConfigNotFound() *AddDebugConfigNotFound {
	return &AddDebugConfigNotFound{}
}

/*AddDebugConfigNotFound handles this case with default header values.

Attachment not found
*/
type AddDebugConfigNotFound struct {
}

func (o *AddDebugConfigNotFound) Error() string {
	return fmt.Sprintf("[POST /debugconfig][%d] addDebugConfigNotFound ", 404)
}

func (o *AddDebugConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddDebugConfigUnprocessableEntity creates a AddDebugConfigUnprocessableEntity with default headers values
func NewAddDebugConfigUnprocessableEntity() *AddDebugConfigUnprocessableEntity {
	return &AddDebugConfigUnprocessableEntity{}
}

/*AddDebugConfigUnprocessableEntity handles this case with default header values.

Invalid input
*/
type AddDebugConfigUnprocessableEntity struct {
}

func (o *AddDebugConfigUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /debugconfig][%d] addDebugConfigUnprocessableEntity ", 422)
}

func (o *AddDebugConfigUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddDebugConfigServiceUnavailable creates a AddDebugConfigServiceUnavailable with default headers values
func NewAddDebugConfigServiceUnavailable() *AddDebugConfigServiceUnavailable {
	return &AddDebugConfigServiceUnavailable{}
}

/*AddDebugConfigServiceUnavailable handles this case with default header values.

Service Unavailable
*/
type AddDebugConfigServiceUnavailable struct {
}

func (o *AddDebugConfigServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /debugconfig][%d] addDebugConfigServiceUnavailable ", 503)
}

func (o *AddDebugConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
