package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDebugConfigParams creates a new DeleteDebugConfigParams object
// with the default values initialized.
func NewDeleteDebugConfigParams() *DeleteDebugConfigParams {
	var ()
	return &DeleteDebugConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDebugConfigParamsWithTimeout creates a new DeleteDebugConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDebugConfigParamsWithTimeout(timeout time.Duration) *DeleteDebugConfigParams {
	var ()
	return &DeleteDebugConfigParams{

		timeout: timeout,
	}
}

// NewDeleteDebugConfigParamsWithContext creates a new DeleteDebugConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDebugConfigParamsWithContext(ctx context.Context) *DeleteDebugConfigParams {
	var ()
	return &DeleteDebugConfigParams{

		Context: ctx,
	}
}

// NewDeleteDebugConfigParamsWithHTTPClient creates a new DeleteDebugConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDebugConfigParamsWithHTTPClient(client *http.Client) *DeleteDebugConfigParams {
	var ()
	return &DeleteDebugConfigParams{
		HTTPClient: client,
	}
}

/*DeleteDebugConfigParams contains all the parameters to send to the API endpoint
for the delete debug config operation typically these are written to a http.Request
*/
type DeleteDebugConfigParams struct {

	/*DebugConfigID
	  ID of config to return

	*/
	DebugConfigID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete debug config params
func (o *DeleteDebugConfigParams) WithTimeout(timeout time.Duration) *DeleteDebugConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete debug config params
func (o *DeleteDebugConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete debug config params
func (o *DeleteDebugConfigParams) WithContext(ctx context.Context) *DeleteDebugConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete debug config params
func (o *DeleteDebugConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete debug config params
func (o *DeleteDebugConfigParams) WithHTTPClient(client *http.Client) *DeleteDebugConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete debug config params
func (o *DeleteDebugConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDebugConfigID adds the debugConfigID to the delete debug config params
func (o *DeleteDebugConfigParams) WithDebugConfigID(debugConfigID string) *DeleteDebugConfigParams {
	o.SetDebugConfigID(debugConfigID)
	return o
}

// SetDebugConfigID adds the debugConfigId to the delete debug config params
func (o *DeleteDebugConfigParams) SetDebugConfigID(debugConfigID string) {
	o.DebugConfigID = debugConfigID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDebugConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param debugConfigId
	if err := r.SetPathParam("debugConfigId", o.DebugConfigID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
