package debugsessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// PopDebugSessionOKCode is the HTTP code returned for type PopDebugSessionOK
const PopDebugSessionOKCode int = 200

/*PopDebugSessionOK Debug session returned

swagger:response popDebugSessionOK
*/
type PopDebugSessionOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugSession `json:"body,omitempty"`
}

// NewPopDebugSessionOK creates PopDebugSessionOK with default headers values
func NewPopDebugSessionOK() *PopDebugSessionOK {
	return &PopDebugSessionOK{}
}

// WithPayload adds the payload to the pop debug session o k response
func (o *PopDebugSessionOK) WithPayload(payload *models.DebugSession) *PopDebugSessionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pop debug session o k response
func (o *PopDebugSessionOK) SetPayload(payload *models.DebugSession) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PopDebugSessionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PopDebugSessionBadRequestCode is the HTTP code returned for type PopDebugSessionBadRequest
const PopDebugSessionBadRequestCode int = 400

/*PopDebugSessionBadRequest Invalid ID supplied

swagger:response popDebugSessionBadRequest
*/
type PopDebugSessionBadRequest struct {
}

// NewPopDebugSessionBadRequest creates PopDebugSessionBadRequest with default headers values
func NewPopDebugSessionBadRequest() *PopDebugSessionBadRequest {
	return &PopDebugSessionBadRequest{}
}

// WriteResponse to the client
func (o *PopDebugSessionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// PopDebugSessionNotFoundCode is the HTTP code returned for type PopDebugSessionNotFound
const PopDebugSessionNotFoundCode int = 404

/*PopDebugSessionNotFound debug config not found

swagger:response popDebugSessionNotFound
*/
type PopDebugSessionNotFound struct {
}

// NewPopDebugSessionNotFound creates PopDebugSessionNotFound with default headers values
func NewPopDebugSessionNotFound() *PopDebugSessionNotFound {
	return &PopDebugSessionNotFound{}
}

// WriteResponse to the client
func (o *PopDebugSessionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// PopDebugSessionRequestTimeoutCode is the HTTP code returned for type PopDebugSessionRequestTimeout
const PopDebugSessionRequestTimeoutCode int = 408

/*PopDebugSessionRequestTimeout Timeout reached

swagger:response popDebugSessionRequestTimeout
*/
type PopDebugSessionRequestTimeout struct {
}

// NewPopDebugSessionRequestTimeout creates PopDebugSessionRequestTimeout with default headers values
func NewPopDebugSessionRequestTimeout() *PopDebugSessionRequestTimeout {
	return &PopDebugSessionRequestTimeout{}
}

// WriteResponse to the client
func (o *PopDebugSessionRequestTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(408)
}
