package debugsessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPopDebugSessionParams creates a new PopDebugSessionParams object
// with the default values initialized.
func NewPopDebugSessionParams() PopDebugSessionParams {
	var ()
	return PopDebugSessionParams{}
}

// PopDebugSessionParams contains all the bound params for the pop debug session operation
// typically these are obtained from a http.Request
//
// swagger:parameters popDebugSession
type PopDebugSessionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: header
	*/
	XTimeout *float64
	/*debug config id.
	  Required: true
	  In: path
	*/
	DebugConfigID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PopDebugSessionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := o.bindXTimeout(r.Header[http.CanonicalHeaderKey("X-Timeout")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rDebugConfigID, rhkDebugConfigID, _ := route.Params.GetOK("debugConfigId")
	if err := o.bindDebugConfigID(rDebugConfigID, rhkDebugConfigID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PopDebugSessionParams) bindXTimeout(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("X-Timeout", "header", "float64", raw)
	}
	o.XTimeout = &value

	return nil
}

func (o *PopDebugSessionParams) bindDebugConfigID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DebugConfigID = raw

	return nil
}
