package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDebugConfigOKCode is the HTTP code returned for type DeleteDebugConfigOK
const DeleteDebugConfigOKCode int = 200

/*DeleteDebugConfigOK OK

swagger:response deleteDebugConfigOK
*/
type DeleteDebugConfigOK struct {
}

// NewDeleteDebugConfigOK creates DeleteDebugConfigOK with default headers values
func NewDeleteDebugConfigOK() *DeleteDebugConfigOK {
	return &DeleteDebugConfigOK{}
}

// WriteResponse to the client
func (o *DeleteDebugConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteDebugConfigBadRequestCode is the HTTP code returned for type DeleteDebugConfigBadRequest
const DeleteDebugConfigBadRequestCode int = 400

/*DeleteDebugConfigBadRequest Invalid ID supplied

swagger:response deleteDebugConfigBadRequest
*/
type DeleteDebugConfigBadRequest struct {
}

// NewDeleteDebugConfigBadRequest creates DeleteDebugConfigBadRequest with default headers values
func NewDeleteDebugConfigBadRequest() *DeleteDebugConfigBadRequest {
	return &DeleteDebugConfigBadRequest{}
}

// WriteResponse to the client
func (o *DeleteDebugConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DeleteDebugConfigNotFoundCode is the HTTP code returned for type DeleteDebugConfigNotFound
const DeleteDebugConfigNotFoundCode int = 404

/*DeleteDebugConfigNotFound Debug config not found

swagger:response deleteDebugConfigNotFound
*/
type DeleteDebugConfigNotFound struct {
}

// NewDeleteDebugConfigNotFound creates DeleteDebugConfigNotFound with default headers values
func NewDeleteDebugConfigNotFound() *DeleteDebugConfigNotFound {
	return &DeleteDebugConfigNotFound{}
}

// WriteResponse to the client
func (o *DeleteDebugConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// DeleteDebugConfigUnprocessableEntityCode is the HTTP code returned for type DeleteDebugConfigUnprocessableEntity
const DeleteDebugConfigUnprocessableEntityCode int = 422

/*DeleteDebugConfigUnprocessableEntity Validation exception

swagger:response deleteDebugConfigUnprocessableEntity
*/
type DeleteDebugConfigUnprocessableEntity struct {
}

// NewDeleteDebugConfigUnprocessableEntity creates DeleteDebugConfigUnprocessableEntity with default headers values
func NewDeleteDebugConfigUnprocessableEntity() *DeleteDebugConfigUnprocessableEntity {
	return &DeleteDebugConfigUnprocessableEntity{}
}

// WriteResponse to the client
func (o *DeleteDebugConfigUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
}
