package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// GetDebugConfigsOKCode is the HTTP code returned for type GetDebugConfigsOK
const GetDebugConfigsOKCode int = 200

/*GetDebugConfigsOK OK

swagger:response getDebugConfigsOK
*/
type GetDebugConfigsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.DebugConfig `json:"body,omitempty"`
}

// NewGetDebugConfigsOK creates GetDebugConfigsOK with default headers values
func NewGetDebugConfigsOK() *GetDebugConfigsOK {
	return &GetDebugConfigsOK{}
}

// WithPayload adds the payload to the get debug configs o k response
func (o *GetDebugConfigsOK) WithPayload(payload []*models.DebugConfig) *GetDebugConfigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get debug configs o k response
func (o *GetDebugConfigsOK) SetPayload(payload []*models.DebugConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDebugConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.DebugConfig, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDebugConfigsBadRequestCode is the HTTP code returned for type GetDebugConfigsBadRequest
const GetDebugConfigsBadRequestCode int = 400

/*GetDebugConfigsBadRequest Invalid ID supplied

swagger:response getDebugConfigsBadRequest
*/
type GetDebugConfigsBadRequest struct {
}

// NewGetDebugConfigsBadRequest creates GetDebugConfigsBadRequest with default headers values
func NewGetDebugConfigsBadRequest() *GetDebugConfigsBadRequest {
	return &GetDebugConfigsBadRequest{}
}

// WriteResponse to the client
func (o *GetDebugConfigsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetDebugConfigsNotFoundCode is the HTTP code returned for type GetDebugConfigsNotFound
const GetDebugConfigsNotFoundCode int = 404

/*GetDebugConfigsNotFound Debug config not found

swagger:response getDebugConfigsNotFound
*/
type GetDebugConfigsNotFound struct {
}

// NewGetDebugConfigsNotFound creates GetDebugConfigsNotFound with default headers values
func NewGetDebugConfigsNotFound() *GetDebugConfigsNotFound {
	return &GetDebugConfigsNotFound{}
}

// WriteResponse to the client
func (o *GetDebugConfigsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// GetDebugConfigsUnprocessableEntityCode is the HTTP code returned for type GetDebugConfigsUnprocessableEntity
const GetDebugConfigsUnprocessableEntityCode int = 422

/*GetDebugConfigsUnprocessableEntity Validation exception

swagger:response getDebugConfigsUnprocessableEntity
*/
type GetDebugConfigsUnprocessableEntity struct {
}

// NewGetDebugConfigsUnprocessableEntity creates GetDebugConfigsUnprocessableEntity with default headers values
func NewGetDebugConfigsUnprocessableEntity() *GetDebugConfigsUnprocessableEntity {
	return &GetDebugConfigsUnprocessableEntity{}
}

// WriteResponse to the client
func (o *GetDebugConfigsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
}
