package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// GetDebugConfigOKCode is the HTTP code returned for type GetDebugConfigOK
const GetDebugConfigOKCode int = 200

/*GetDebugConfigOK OK

swagger:response getDebugConfigOK
*/
type GetDebugConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugConfig `json:"body,omitempty"`
}

// NewGetDebugConfigOK creates GetDebugConfigOK with default headers values
func NewGetDebugConfigOK() *GetDebugConfigOK {
	return &GetDebugConfigOK{}
}

// WithPayload adds the payload to the get debug config o k response
func (o *GetDebugConfigOK) WithPayload(payload *models.DebugConfig) *GetDebugConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get debug config o k response
func (o *GetDebugConfigOK) SetPayload(payload *models.DebugConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDebugConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDebugConfigBadRequestCode is the HTTP code returned for type GetDebugConfigBadRequest
const GetDebugConfigBadRequestCode int = 400

/*GetDebugConfigBadRequest Invalid ID supplied

swagger:response getDebugConfigBadRequest
*/
type GetDebugConfigBadRequest struct {
}

// NewGetDebugConfigBadRequest creates GetDebugConfigBadRequest with default headers values
func NewGetDebugConfigBadRequest() *GetDebugConfigBadRequest {
	return &GetDebugConfigBadRequest{}
}

// WriteResponse to the client
func (o *GetDebugConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetDebugConfigNotFoundCode is the HTTP code returned for type GetDebugConfigNotFound
const GetDebugConfigNotFoundCode int = 404

/*GetDebugConfigNotFound Debug config not found

swagger:response getDebugConfigNotFound
*/
type GetDebugConfigNotFound struct {
}

// NewGetDebugConfigNotFound creates GetDebugConfigNotFound with default headers values
func NewGetDebugConfigNotFound() *GetDebugConfigNotFound {
	return &GetDebugConfigNotFound{}
}

// WriteResponse to the client
func (o *GetDebugConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// GetDebugConfigUnprocessableEntityCode is the HTTP code returned for type GetDebugConfigUnprocessableEntity
const GetDebugConfigUnprocessableEntityCode int = 422

/*GetDebugConfigUnprocessableEntity Validation exception

swagger:response getDebugConfigUnprocessableEntity
*/
type GetDebugConfigUnprocessableEntity struct {
}

// NewGetDebugConfigUnprocessableEntity creates GetDebugConfigUnprocessableEntity with default headers values
func NewGetDebugConfigUnprocessableEntity() *GetDebugConfigUnprocessableEntity {
	return &GetDebugConfigUnprocessableEntity{}
}

// WriteResponse to the client
func (o *GetDebugConfigUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
}
