package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// PopContainerToDebugOKCode is the HTTP code returned for type PopContainerToDebugOK
const PopContainerToDebugOKCode int = 200

/*PopContainerToDebugOK OK

swagger:response popContainerToDebugOK
*/
type PopContainerToDebugOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugConfig `json:"body,omitempty"`
}

// NewPopContainerToDebugOK creates PopContainerToDebugOK with default headers values
func NewPopContainerToDebugOK() *PopContainerToDebugOK {
	return &PopContainerToDebugOK{}
}

// WithPayload adds the payload to the pop container to debug o k response
func (o *PopContainerToDebugOK) WithPayload(payload *models.DebugConfig) *PopContainerToDebugOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pop container to debug o k response
func (o *PopContainerToDebugOK) SetPayload(payload *models.DebugConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PopContainerToDebugOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PopContainerToDebugBadRequestCode is the HTTP code returned for type PopContainerToDebugBadRequest
const PopContainerToDebugBadRequestCode int = 400

/*PopContainerToDebugBadRequest Invalid ID supplied

swagger:response popContainerToDebugBadRequest
*/
type PopContainerToDebugBadRequest struct {
}

// NewPopContainerToDebugBadRequest creates PopContainerToDebugBadRequest with default headers values
func NewPopContainerToDebugBadRequest() *PopContainerToDebugBadRequest {
	return &PopContainerToDebugBadRequest{}
}

// WriteResponse to the client
func (o *PopContainerToDebugBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// PopContainerToDebugNotFoundCode is the HTTP code returned for type PopContainerToDebugNotFound
const PopContainerToDebugNotFoundCode int = 404

/*PopContainerToDebugNotFound Node note not found

swagger:response popContainerToDebugNotFound
*/
type PopContainerToDebugNotFound struct {
}

// NewPopContainerToDebugNotFound creates PopContainerToDebugNotFound with default headers values
func NewPopContainerToDebugNotFound() *PopContainerToDebugNotFound {
	return &PopContainerToDebugNotFound{}
}

// WriteResponse to the client
func (o *PopContainerToDebugNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// PopContainerToDebugRequestTimeoutCode is the HTTP code returned for type PopContainerToDebugRequestTimeout
const PopContainerToDebugRequestTimeoutCode int = 408

/*PopContainerToDebugRequestTimeout Timeout reached

swagger:response popContainerToDebugRequestTimeout
*/
type PopContainerToDebugRequestTimeout struct {
}

// NewPopContainerToDebugRequestTimeout creates PopContainerToDebugRequestTimeout with default headers values
func NewPopContainerToDebugRequestTimeout() *PopContainerToDebugRequestTimeout {
	return &PopContainerToDebugRequestTimeout{}
}

// WriteResponse to the client
func (o *PopContainerToDebugRequestTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(408)
}
