package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// UpdateDebugConfigOKCode is the HTTP code returned for type UpdateDebugConfigOK
const UpdateDebugConfigOKCode int = 200

/*UpdateDebugConfigOK OK

swagger:response updateDebugConfigOK
*/
type UpdateDebugConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.DebugConfig `json:"body,omitempty"`
}

// NewUpdateDebugConfigOK creates UpdateDebugConfigOK with default headers values
func NewUpdateDebugConfigOK() *UpdateDebugConfigOK {
	return &UpdateDebugConfigOK{}
}

// WithPayload adds the payload to the update debug config o k response
func (o *UpdateDebugConfigOK) WithPayload(payload *models.DebugConfig) *UpdateDebugConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update debug config o k response
func (o *UpdateDebugConfigOK) SetPayload(payload *models.DebugConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDebugConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDebugConfigBadRequestCode is the HTTP code returned for type UpdateDebugConfigBadRequest
const UpdateDebugConfigBadRequestCode int = 400

/*UpdateDebugConfigBadRequest Invalid ID supplied

swagger:response updateDebugConfigBadRequest
*/
type UpdateDebugConfigBadRequest struct {
}

// NewUpdateDebugConfigBadRequest creates UpdateDebugConfigBadRequest with default headers values
func NewUpdateDebugConfigBadRequest() *UpdateDebugConfigBadRequest {
	return &UpdateDebugConfigBadRequest{}
}

// WriteResponse to the client
func (o *UpdateDebugConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateDebugConfigNotFoundCode is the HTTP code returned for type UpdateDebugConfigNotFound
const UpdateDebugConfigNotFoundCode int = 404

/*UpdateDebugConfigNotFound Debug config not found

swagger:response updateDebugConfigNotFound
*/
type UpdateDebugConfigNotFound struct {
}

// NewUpdateDebugConfigNotFound creates UpdateDebugConfigNotFound with default headers values
func NewUpdateDebugConfigNotFound() *UpdateDebugConfigNotFound {
	return &UpdateDebugConfigNotFound{}
}

// WriteResponse to the client
func (o *UpdateDebugConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// UpdateDebugConfigUnprocessableEntityCode is the HTTP code returned for type UpdateDebugConfigUnprocessableEntity
const UpdateDebugConfigUnprocessableEntityCode int = 422

/*UpdateDebugConfigUnprocessableEntity Validation exception

swagger:response updateDebugConfigUnprocessableEntity
*/
type UpdateDebugConfigUnprocessableEntity struct {
}

// NewUpdateDebugConfigUnprocessableEntity creates UpdateDebugConfigUnprocessableEntity with default headers values
func NewUpdateDebugConfigUnprocessableEntity() *UpdateDebugConfigUnprocessableEntity {
	return &UpdateDebugConfigUnprocessableEntity{}
}

// WriteResponse to the client
func (o *UpdateDebugConfigUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
}
