package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/solo-io/squash/pkg/models"
)

// NewUpdateDebugConfigParams creates a new UpdateDebugConfigParams object
// with the default values initialized.
func NewUpdateDebugConfigParams() UpdateDebugConfigParams {
	var ()
	return UpdateDebugConfigParams{}
}

// UpdateDebugConfigParams contains all the bound params for the update debug config operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateDebugConfig
type UpdateDebugConfigParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*debug config edited
	  Required: true
	  In: body
	*/
	Body *models.DebugConfig
	/*ID of config to return
	  Required: true
	  In: path
	*/
	DebugConfigID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateDebugConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DebugConfig
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	rDebugConfigID, rhkDebugConfigID, _ := route.Params.GetOK("debugConfigId")
	if err := o.bindDebugConfigID(rDebugConfigID, rhkDebugConfigID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateDebugConfigParams) bindDebugConfigID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DebugConfigID = raw

	return nil
}
