package debugconfig

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDebugConfigHandlerFunc turns a function with the right signature into a update debug config handler
type UpdateDebugConfigHandlerFunc func(UpdateDebugConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDebugConfigHandlerFunc) Handle(params UpdateDebugConfigParams) middleware.Responder {
	return fn(params)
}

// UpdateDebugConfigHandler interface for that can handle valid update debug config params
type UpdateDebugConfigHandler interface {
	Handle(UpdateDebugConfigParams) middleware.Responder
}

// NewUpdateDebugConfig creates a new http.Handler for the update debug config operation
func NewUpdateDebugConfig(ctx *middleware.Context, handler UpdateDebugConfigHandler) *UpdateDebugConfig {
	return &UpdateDebugConfig{Context: ctx, Handler: handler}
}

/*UpdateDebugConfig swagger:route PATCH /debugconfig/{debugConfigId} debugconfig updateDebugConfig

Update an existing debug config

*/
type UpdateDebugConfig struct {
	Context *middleware.Context
	Handler UpdateDebugConfigHandler
}

func (o *UpdateDebugConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateDebugConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
