// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/solo-io/squash/pkg/models"
)

// CreateDebugRequestCreatedCode is the HTTP code returned for type CreateDebugRequestCreated
const CreateDebugRequestCreatedCode int = 201

/*CreateDebugRequestCreated OK

swagger:response createDebugRequestCreated
*/
type CreateDebugRequestCreated struct {

	/*
	  In: Body
	*/
	Payload *models.DebugRequest `json:"body,omitempty"`
}

// NewCreateDebugRequestCreated creates CreateDebugRequestCreated with default headers values
func NewCreateDebugRequestCreated() *CreateDebugRequestCreated {
	return &CreateDebugRequestCreated{}
}

// WithPayload adds the payload to the create debug request created response
func (o *CreateDebugRequestCreated) WithPayload(payload *models.DebugRequest) *CreateDebugRequestCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create debug request created response
func (o *CreateDebugRequestCreated) SetPayload(payload *models.DebugRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDebugRequestCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
