// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDebugRequestOKCode is the HTTP code returned for type DeleteDebugRequestOK
const DeleteDebugRequestOKCode int = 200

/*DeleteDebugRequestOK OK

swagger:response deleteDebugRequestOK
*/
type DeleteDebugRequestOK struct {
}

// NewDeleteDebugRequestOK creates DeleteDebugRequestOK with default headers values
func NewDeleteDebugRequestOK() *DeleteDebugRequestOK {
	return &DeleteDebugRequestOK{}
}

// WriteResponse to the client
func (o *DeleteDebugRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteDebugRequestBadRequestCode is the HTTP code returned for type DeleteDebugRequestBadRequest
const DeleteDebugRequestBadRequestCode int = 400

/*DeleteDebugRequestBadRequest Invalid ID supplied

swagger:response deleteDebugRequestBadRequest
*/
type DeleteDebugRequestBadRequest struct {
}

// NewDeleteDebugRequestBadRequest creates DeleteDebugRequestBadRequest with default headers values
func NewDeleteDebugRequestBadRequest() *DeleteDebugRequestBadRequest {
	return &DeleteDebugRequestBadRequest{}
}

// WriteResponse to the client
func (o *DeleteDebugRequestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteDebugRequestNotFoundCode is the HTTP code returned for type DeleteDebugRequestNotFound
const DeleteDebugRequestNotFoundCode int = 404

/*DeleteDebugRequestNotFound Debug request not found

swagger:response deleteDebugRequestNotFound
*/
type DeleteDebugRequestNotFound struct {
}

// NewDeleteDebugRequestNotFound creates DeleteDebugRequestNotFound with default headers values
func NewDeleteDebugRequestNotFound() *DeleteDebugRequestNotFound {
	return &DeleteDebugRequestNotFound{}
}

// WriteResponse to the client
func (o *DeleteDebugRequestNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteDebugRequestUnprocessableEntityCode is the HTTP code returned for type DeleteDebugRequestUnprocessableEntity
const DeleteDebugRequestUnprocessableEntityCode int = 422

/*DeleteDebugRequestUnprocessableEntity Validation exception

swagger:response deleteDebugRequestUnprocessableEntity
*/
type DeleteDebugRequestUnprocessableEntity struct {
}

// NewDeleteDebugRequestUnprocessableEntity creates DeleteDebugRequestUnprocessableEntity with default headers values
func NewDeleteDebugRequestUnprocessableEntity() *DeleteDebugRequestUnprocessableEntity {
	return &DeleteDebugRequestUnprocessableEntity{}
}

// WriteResponse to the client
func (o *DeleteDebugRequestUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
