// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDebugRequestParams creates a new DeleteDebugRequestParams object
// with the default values initialized.
func NewDeleteDebugRequestParams() DeleteDebugRequestParams {
	var ()
	return DeleteDebugRequestParams{}
}

// DeleteDebugRequestParams contains all the bound params for the delete debug request operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteDebugRequest
type DeleteDebugRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of debug request
	  Required: true
	  In: path
	*/
	DebugRequestID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteDebugRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rDebugRequestID, rhkDebugRequestID, _ := route.Params.GetOK("debugRequestId")
	if err := o.bindDebugRequestID(rDebugRequestID, rhkDebugRequestID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDebugRequestParams) bindDebugRequestID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DebugRequestID = raw

	return nil
}
