// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDebugRequestHandlerFunc turns a function with the right signature into a delete debug request handler
type DeleteDebugRequestHandlerFunc func(DeleteDebugRequestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDebugRequestHandlerFunc) Handle(params DeleteDebugRequestParams) middleware.Responder {
	return fn(params)
}

// DeleteDebugRequestHandler interface for that can handle valid delete debug request params
type DeleteDebugRequestHandler interface {
	Handle(DeleteDebugRequestParams) middleware.Responder
}

// NewDeleteDebugRequest creates a new http.Handler for the delete debug request operation
func NewDeleteDebugRequest(ctx *middleware.Context, handler DeleteDebugRequestHandler) *DeleteDebugRequest {
	return &DeleteDebugRequest{Context: ctx, Handler: handler}
}

/*DeleteDebugRequest swagger:route DELETE /debugrequest/{debugRequestId} debugrequest deleteDebugRequest

Delete a debug request

Delete a debug request.

*/
type DeleteDebugRequest struct {
	Context *middleware.Context
	Handler DeleteDebugRequestHandler
}

func (o *DeleteDebugRequest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDebugRequestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
