// Code generated by go-swagger; DO NOT EDIT.

package debugrequest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDebugRequestsHandlerFunc turns a function with the right signature into a get debug requests handler
type GetDebugRequestsHandlerFunc func(GetDebugRequestsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDebugRequestsHandlerFunc) Handle(params GetDebugRequestsParams) middleware.Responder {
	return fn(params)
}

// GetDebugRequestsHandler interface for that can handle valid get debug requests params
type GetDebugRequestsHandler interface {
	Handle(GetDebugRequestsParams) middleware.Responder
}

// NewGetDebugRequests creates a new http.Handler for the get debug requests operation
func NewGetDebugRequests(ctx *middleware.Context, handler GetDebugRequestsHandler) *GetDebugRequests {
	return &GetDebugRequests{Context: ctx, Handler: handler}
}

/*GetDebugRequests swagger:route GET /debugrequest debugrequest getDebugRequests

Return all debug request

Return all debug requests

*/
type GetDebugRequests struct {
	Context *middleware.Context
	Handler GetDebugRequestsHandler
}

func (o *GetDebugRequests) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDebugRequestsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
