FROM golang:1.10.1-stretch as builder

RUN mkdir -p $GOPATH/src/github.com/derekparker/ && cd  $GOPATH/src/github.com/derekparker/ && git clone https://github.com/yuval-k/delve/
RUN cd $GOPATH/src/github.com/derekparker/delve/ && git checkout fix-sigsegv
RUN cd $GOPATH/src/github.com/derekparker/delve/cmd/dlv && go install


FROM golang:1.10.1-stretch

COPY --from=builder $GOPATH/bin/dlv $GOPATH/bin/

ENV DEBUGGER=dlv
COPY squash-lite-container /
ENTRYPOINT ["/squash-lite-container"]
